package com.medwin.landison.kms.reservationservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-10-19T17:37:49.909+08:00
 * Generated source version: 3.2.6
 *
 */
@WebServiceClient(name = "Reservation",
                  wsdlLocation = "file:/E:/github/landison/src/main/java/com/medwin/landison/kms/reservationservice/ReservationService.asmx",
                  targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
public class Reservation extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.shijinet.com.cn/kunlun/kws/1.1/", "Reservation");
    public final static QName ReservationSoap = new QName("http://www.shijinet.com.cn/kunlun/kws/1.1/", "ReservationSoap");
    static {
        URL url = null;
        try {
            url = new URL("file:/E:/github/landison/src/main/java/com/medwin/landison/kms/reservationservice/ReservationService.asmx");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Reservation.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/E:/github/landison/src/main/java/com/medwin/landison/kms/reservationservice/ReservationService.asmx");
        }
        WSDL_LOCATION = url;
    }

    public Reservation(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Reservation(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Reservation() {
        super(WSDL_LOCATION, SERVICE);
    }

    public Reservation(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public Reservation(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public Reservation(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ReservationSoap
     */
    @WebEndpoint(name = "ReservationSoap")
    public ReservationSoap getReservationSoap() {
        return super.getPort(ReservationSoap, ReservationSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReservationSoap
     */
    @WebEndpoint(name = "ReservationSoap")
    public ReservationSoap getReservationSoap(WebServiceFeature... features) {
        return super.getPort(ReservationSoap, ReservationSoap.class, features);
    }

}
