package com.medwin.landison.kms.reservationservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-10-19T17:37:49.866+08:00
 * Generated source version: 3.2.6
 *
 */
@WebService(targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", name = "ReservationSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface ReservationSoap {

    /**
     * 根据订单号判断该订单是否可以使用自助入住功能,和自助check-in系统配合使用
     */
    @WebMethod(operationName = "SelfCheckInAllowed", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/SelfCheckInAllowed")
    @RequestWrapper(localName = "SelfCheckInAllowed", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.SelfCheckInAllowed")
    @ResponseWrapper(localName = "SelfCheckInAllowedResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.SelfCheckInAllowedResponse")
    @WebResult(name = "SelfCheckInAllowedResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.reservationservice.SelfCheckInAllowedInfo selfCheckInAllowed(
        @WebParam(name = "id", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        int id
    );

    /**
     * 查询某个订单的alert信息
     */
    @WebMethod(operationName = "GetOrderInfoAlert", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetOrderInfoAlert")
    @RequestWrapper(localName = "GetOrderInfoAlert", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.GetOrderInfoAlert")
    @ResponseWrapper(localName = "GetOrderInfoAlertResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.GetOrderInfoAlertResponse")
    @WebResult(name = "GetOrderInfoAlertResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.reservationservice.GetOrderInfoAlertOut getOrderInfoAlert(
        @WebParam(name = "getOrderInfoAlertIn", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        com.medwin.landison.kms.reservationservice.GetOrderInfoAlertIn getOrderInfoAlertIn
    );

    /**
     * 保存订单的trace信息,SaveAction:新增(ADD),修改(UPDATE),删除(DELETE)
     */
    @WebMethod(operationName = "SaveOrderInfoTrace", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/SaveOrderInfoTrace")
    @RequestWrapper(localName = "SaveOrderInfoTrace", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.SaveOrderInfoTrace")
    @ResponseWrapper(localName = "SaveOrderInfoTraceResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.SaveOrderInfoTraceResponse")
    @WebResult(name = "SaveOrderInfoTraceResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.reservationservice.SaveOrderInfoTraceOut saveOrderInfoTrace(
        @WebParam(name = "saveOrderInfoTraceIn", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        com.medwin.landison.kms.reservationservice.SaveOrderInfoTraceIn saveOrderInfoTraceIn
    );

    /**
     * 查询公司或会员订单,输入:客人类型,帐号，起始日期,结束日期
     */
    @WebMethod(operationName = "GetOrderInfoByGuestType", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetOrderInfoByGuestType")
    @RequestWrapper(localName = "GetOrderInfoByGuestType", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.GetOrderInfoByGuestType")
    @ResponseWrapper(localName = "GetOrderInfoByGuestTypeResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.GetOrderInfoByGuestTypeResponse")
    @WebResult(name = "GetOrderInfoByGuestTypeResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.reservationservice.ArrayOfOrderInfo getOrderInfoByGuestType(
        @WebParam(name = "guestType", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String guestType,
        @WebParam(name = "account", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String account,
        @WebParam(name = "beginMakedate", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        javax.xml.datatype.XMLGregorianCalendar beginMakedate,
        @WebParam(name = "endMakedate", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        javax.xml.datatype.XMLGregorianCalendar endMakedate
    );

    /**
     * 添加、修改第三方支付信息（如网银支付流水，是否成功）
     */
    @WebMethod(operationName = "AddAndUpdateOrderInfoPaymentGateway", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/AddAndUpdateOrderInfoPaymentGateway")
    @RequestWrapper(localName = "AddAndUpdateOrderInfoPaymentGateway", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.AddAndUpdateOrderInfoPaymentGateway")
    @ResponseWrapper(localName = "AddAndUpdateOrderInfoPaymentGatewayResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.AddAndUpdateOrderInfoPaymentGatewayResponse")
    @WebResult(name = "AddAndUpdateOrderInfoPaymentGatewayResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.reservationservice.OrderInfoPaymentGateway addAndUpdateOrderInfoPaymentGateway(
        @WebParam(name = "paymentGateway", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        com.medwin.landison.kms.reservationservice.OrderInfoPaymentGateway paymentGateway,
        @WebParam(name = "id", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.Integer id,
        @WebParam(name = "isRequiredCredit", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        boolean isRequiredCredit,
        @WebParam(name = "creditId", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String creditId,
        @WebParam(name = "cardHolder", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String cardHolder,
        @WebParam(name = "expire", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        javax.xml.datatype.XMLGregorianCalendar expire,
        @WebParam(name = "isCancelPayment", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        boolean isCancelPayment
    );

    /**
     * 查询单个订单的修改记录,输入订单号
     */
    @WebMethod(operationName = "GetOrderLogs", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetOrderLogs")
    @RequestWrapper(localName = "GetOrderLogs", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.GetOrderLogs")
    @ResponseWrapper(localName = "GetOrderLogsResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.GetOrderLogsResponse")
    @WebResult(name = "GetOrderLogsResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.reservationservice.ArrayOfOrderLog getOrderLogs(
        @WebParam(name = "id", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        int id
    );

    /**
     * 按条件查询订单,输入:订单号（其中如果id=-1表示查询所有渠道服务条件的订单，如果为0表示获取该渠道符合条件的订单，其他表示获取对应订单号的订单）,预定起始时间,预定结束时间,入住日期,离店日期,订单状态,担保方式,酒店code,firstname,lastname,员工编号,公司预订登陆帐号,客人类型
     */
    @WebMethod(operationName = "OrderQuery", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/OrderQuery")
    @RequestWrapper(localName = "OrderQuery", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.OrderQuery")
    @ResponseWrapper(localName = "OrderQueryResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.OrderQueryResponse")
    @WebResult(name = "OrderQueryResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.reservationservice.ArrayOfOrderInfo orderQuery(
        @WebParam(name = "id", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        int id,
        @WebParam(name = "beginMakedate", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        javax.xml.datatype.XMLGregorianCalendar beginMakedate,
        @WebParam(name = "endMakedate", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        javax.xml.datatype.XMLGregorianCalendar endMakedate,
        @WebParam(name = "arrival", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        javax.xml.datatype.XMLGregorianCalendar arrival,
        @WebParam(name = "departure", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        javax.xml.datatype.XMLGregorianCalendar departure,
        @WebParam(name = "status_code", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String statusCode,
        @WebParam(name = "reservation_type", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String reservationType,
        @WebParam(name = "hotel_code", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String hotelCode,
        @WebParam(name = "firstname", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String firstname,
        @WebParam(name = "lastname", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String lastname,
        @WebParam(name = "guest_id", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String guestId,
        @WebParam(name = "account", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String account,
        @WebParam(name = "guestType", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String guestType
    );

    /**
     * 保存订单的alert信息,SaveAction:新增(ADD),修改(UPDATE),删除(DELETE)
     */
    @WebMethod(operationName = "SaveOrderInfoAlert", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/SaveOrderInfoAlert")
    @RequestWrapper(localName = "SaveOrderInfoAlert", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.SaveOrderInfoAlert")
    @ResponseWrapper(localName = "SaveOrderInfoAlertResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.SaveOrderInfoAlertResponse")
    @WebResult(name = "SaveOrderInfoAlertResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.reservationservice.SaveOrderInfoAlertOut saveOrderInfoAlert(
        @WebParam(name = "saveOrderInfoAlertIn", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        com.medwin.landison.kms.reservationservice.SaveOrderInfoAlertIn saveOrderInfoAlertIn
    );

    /**
     * 查询单个订单,输入订单号
     */
    @WebMethod(operationName = "GetOrderInfo", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetOrderInfo")
    @RequestWrapper(localName = "GetOrderInfo", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.GetOrderInfo")
    @ResponseWrapper(localName = "GetOrderInfoResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.GetOrderInfoResponse")
    @WebResult(name = "GetOrderInfoResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.reservationservice.OrderInfo getOrderInfo(
        @WebParam(name = "id", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        int id
    );

    /**
     * 取消订单原因
     */
    @WebMethod(operationName = "AddGiveUpOrderReserveReason", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/AddGiveUpOrderReserveReason")
    @RequestWrapper(localName = "AddGiveUpOrderReserveReason", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.AddGiveUpOrderReserveReason")
    @ResponseWrapper(localName = "AddGiveUpOrderReserveReasonResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.AddGiveUpOrderReserveReasonResponse")
    @WebResult(name = "AddGiveUpOrderReserveReasonResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.reservationservice.GiveUpOrderReserveReasonOut addGiveUpOrderReserveReason(
        @WebParam(name = "cOrderReason", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        com.medwin.landison.kms.reservationservice.GiveUpOrderReserveReasonIn cOrderReason
    );

    /**
     * 变更订单状态
     */
    @WebMethod(operationName = "ChangeReservationStatus", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/ChangeReservationStatus")
    @RequestWrapper(localName = "ChangeReservationStatus", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.ChangeReservationStatus")
    @ResponseWrapper(localName = "ChangeReservationStatusResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.ChangeReservationStatusResponse")
    @WebResult(name = "ChangeReservationStatusResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public boolean changeReservationStatus(
        @WebParam(name = "status", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        com.medwin.landison.kms.reservationservice.ResvStatus status,
        @WebParam(name = "order_id", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        int orderId
    );

    /**
     * Pegasus取消订单,输入订单id,取消原因,渠道取消号
     */
    @WebMethod(operationName = "PegasusCancelReservation", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/PegasusCancelReservation")
    @RequestWrapper(localName = "PegasusCancelReservation", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.PegasusCancelReservation")
    @ResponseWrapper(localName = "PegasusCancelReservationResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.PegasusCancelReservationResponse")
    @WebResult(name = "PegasusCancelReservationResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public boolean pegasusCancelReservation(
        @WebParam(name = "id", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        int id,
        @WebParam(name = "comments", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String comments,
        @WebParam(name = "channelCancelID", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String channelCancelID
    );

    /**
     * 查找对应订单ID的取消规则
     */
    @WebMethod(operationName = "GetCancelRuleByOrderId", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetCancelRuleByOrderId")
    @RequestWrapper(localName = "GetCancelRuleByOrderId", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.GetCancelRuleByOrderId")
    @ResponseWrapper(localName = "GetCancelRuleByOrderIdResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.GetCancelRuleByOrderIdResponse")
    @WebResult(name = "GetCancelRuleByOrderIdResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.reservationservice.CancelRule getCancelRuleByOrderId(
        @WebParam(name = "orderId", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String orderId
    );

    /**
     * 查询散客订单,输入订单号，Email
     */
    @WebMethod(operationName = "GetOrderInfoByEmailAndID", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetOrderInfoByEmailAndID")
    @RequestWrapper(localName = "GetOrderInfoByEmailAndID", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.GetOrderInfoByEmailAndID")
    @ResponseWrapper(localName = "GetOrderInfoByEmailAndIDResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.GetOrderInfoByEmailAndIDResponse")
    @WebResult(name = "GetOrderInfoByEmailAndIDResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.reservationservice.OrderInfo getOrderInfoByEmailAndID(
        @WebParam(name = "id", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        int id,
        @WebParam(name = "email", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String email
    );

    /**
     * 添加第三方支付信息（如网银支付流水，是否成功）
     */
    @WebMethod(operationName = "AddorderInfoPaymentGateway", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/AddorderInfoPaymentGateway")
    @RequestWrapper(localName = "AddorderInfoPaymentGateway", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.AddorderInfoPaymentGateway")
    @ResponseWrapper(localName = "AddorderInfoPaymentGatewayResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.AddorderInfoPaymentGatewayResponse")
    @WebResult(name = "AddorderInfoPaymentGatewayResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.reservationservice.OrderInfoPaymentGateway addorderInfoPaymentGateway(
        @WebParam(name = "paymentGateway", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        com.medwin.landison.kms.reservationservice.OrderInfoPaymentGateway paymentGateway
    );

    /**
     * 修改Pegasus订单,输入OrderInfo,输出OrderInfo
     */
    @WebMethod(operationName = "PegasusModifyReservation", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/PegasusModifyReservation")
    @RequestWrapper(localName = "PegasusModifyReservation", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.PegasusModifyReservation")
    @ResponseWrapper(localName = "PegasusModifyReservationResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.PegasusModifyReservationResponse")
    @WebResult(name = "PegasusModifyReservationResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.reservationservice.OrderInfo pegasusModifyReservation(
        @WebParam(name = "oOrderInfo", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        com.medwin.landison.kms.reservationservice.OrderInfo oOrderInfo
    );

    /**
     * 取消订单,输入订单id,取消原因
     */
    @WebMethod(operationName = "CancelOrder", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/CancelOrder")
    @RequestWrapper(localName = "CancelOrder", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.CancelOrder")
    @ResponseWrapper(localName = "CancelOrderResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.CancelOrderResponse")
    @WebResult(name = "CancelOrderResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public boolean cancelOrder(
        @WebParam(name = "id", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        int id,
        @WebParam(name = "comments", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String comments,
        @WebParam(name = "croPermission", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String croPermission
    );

    /**
     * 查询多个订单,输入:订单号,预定起始时间,预定结束时间,入住日期,离店日期,订单状态,担保方式,酒店code,firstname,lastname,员工编号,公司预订登陆帐号,客人类型,每页数量,第几页
     */
    @WebMethod(operationName = "OrderQueryPerPage", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/OrderQueryPerPage")
    @RequestWrapper(localName = "OrderQueryPerPage", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.OrderQueryPerPage")
    @ResponseWrapper(localName = "OrderQueryPerPageResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.OrderQueryPerPageResponse")
    @WebResult(name = "OrderQueryPerPageResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.reservationservice.ExtraOrderInfoSummary orderQueryPerPage(
        @WebParam(name = "id", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        int id,
        @WebParam(name = "beginMakedate", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        javax.xml.datatype.XMLGregorianCalendar beginMakedate,
        @WebParam(name = "endMakedate", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        javax.xml.datatype.XMLGregorianCalendar endMakedate,
        @WebParam(name = "arrival", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        javax.xml.datatype.XMLGregorianCalendar arrival,
        @WebParam(name = "departure", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        javax.xml.datatype.XMLGregorianCalendar departure,
        @WebParam(name = "status_code", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String statusCode,
        @WebParam(name = "reservation_type", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String reservationType,
        @WebParam(name = "hotel_code", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String hotelCode,
        @WebParam(name = "firstname", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String firstname,
        @WebParam(name = "lastname", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String lastname,
        @WebParam(name = "guest_id", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String guestId,
        @WebParam(name = "account", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String account,
        @WebParam(name = "guestType", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String guestType,
        @WebParam(name = "pageSize", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        int pageSize,
        @WebParam(name = "currentPage", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        int currentPage
    );

    /**
     * 恢复订单到预定状态
     */
    @WebMethod(operationName = "RestoreReservation", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/RestoreReservation")
    @RequestWrapper(localName = "RestoreReservation", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.RestoreReservation")
    @ResponseWrapper(localName = "RestoreReservationResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.RestoreReservationResponse")
    @WebResult(name = "RestoreReservationResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.reservationservice.RestoreReservationOut restoreReservation(
        @WebParam(name = "restoreReservationIn", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        com.medwin.landison.kms.reservationservice.RestoreReservationIn restoreReservationIn
    );

    /**
     * 查询订单提醒信息
     */
    @WebMethod(operationName = "GetOrderAlertList", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetOrderAlertList")
    @RequestWrapper(localName = "GetOrderAlertList", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.GetOrderAlertList")
    @ResponseWrapper(localName = "GetOrderAlertListResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.GetOrderAlertListResponse")
    @WebResult(name = "GetOrderAlertListResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.reservationservice.OrderAlertOut getOrderAlertList(
        @WebParam(name = "orderAlertIn", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        com.medwin.landison.kms.reservationservice.OrderAlertIn orderAlertIn
    );

    /**
     * 变更订单状态
     */
    @WebMethod(operationName = "ChangeOrderStatus", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/ChangeOrderStatus")
    @RequestWrapper(localName = "ChangeOrderStatus", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.ChangeOrderStatus")
    @ResponseWrapper(localName = "ChangeOrderStatusResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.ChangeOrderStatusResponse")
    @WebResult(name = "ChangeOrderStatusResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public boolean changeOrderStatus(
        @WebParam(name = "status", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        com.medwin.landison.kms.reservationservice.ResvStatus status,
        @WebParam(name = "order_id", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        int orderId,
        @WebParam(name = "croPermission", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String croPermission
    );

    /**
     * 分页查询多个订单,输入:订单号,到店开始、结束时间，离店开始、结束时间，酒店，FirstName，LastName，客户协议号，会员卡号，查询页数，每页行数
     */
    @WebMethod(operationName = "QueryOrderPage", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/QueryOrderPage")
    @RequestWrapper(localName = "QueryOrderPage", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.QueryOrderPage")
    @ResponseWrapper(localName = "QueryOrderPageResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.QueryOrderPageResponse")
    @WebResult(name = "QueryOrderPageResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.reservationservice.QueryOrderPageOut queryOrderPage(
        @WebParam(name = "request", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        com.medwin.landison.kms.reservationservice.QueryOrderPageIn request
    );

    /**
     * 将一个已经存在PARTY关系的订单修改其PARTY关系并关联到另一个PARTY中
     */
    @WebMethod(operationName = "ChangeOrderToParty", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/ChangeOrderToParty")
    @RequestWrapper(localName = "ChangeOrderToParty", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.ChangeOrderToParty")
    @ResponseWrapper(localName = "ChangeOrderToPartyResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.ChangeOrderToPartyResponse")
    @WebResult(name = "ChangeOrderToPartyResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.reservationservice.ChangeOrderToPartyOut changeOrderToParty(
        @WebParam(name = "request", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        com.medwin.landison.kms.reservationservice.ChangeOrderToPartyIn request
    );

    /**
     * 查询订单折扣信息
     */
    @WebMethod(operationName = "GetOrderInfoDiscounts", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetOrderInfoDiscounts")
    @RequestWrapper(localName = "GetOrderInfoDiscounts", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.GetOrderInfoDiscounts")
    @ResponseWrapper(localName = "GetOrderInfoDiscountsResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.GetOrderInfoDiscountsResponse")
    @WebResult(name = "GetOrderInfoDiscountsResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.reservationservice.ArrayOfOrderInfoDiscount getOrderInfoDiscounts(
        @WebParam(name = "orderID", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        int orderID
    );

    /**
     * 取消订单,输入订单id,取消原因
     */
    @WebMethod(operationName = "CancelReservation", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/CancelReservation")
    @RequestWrapper(localName = "CancelReservation", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.CancelReservation")
    @ResponseWrapper(localName = "CancelReservationResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.CancelReservationResponse")
    @WebResult(name = "CancelReservationResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public boolean cancelReservation(
        @WebParam(name = "id", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        int id,
        @WebParam(name = "comments", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String comments
    );

    /**
     * 修改订单,输入OrderInfo,输出OrderInfo
     */
    @WebMethod(operationName = "ModifyReservation", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/ModifyReservation")
    @RequestWrapper(localName = "ModifyReservation", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.ModifyReservation")
    @ResponseWrapper(localName = "ModifyReservationResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.ModifyReservationResponse")
    @WebResult(name = "ModifyReservationResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.reservationservice.OrderInfo modifyReservation(
        @WebParam(name = "oOrderInfo", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        com.medwin.landison.kms.reservationservice.OrderInfo oOrderInfo
    );

    /**
     * 根据Pegasus PNR号获取订单号
     */
    @WebMethod(operationName = "GetOrderID", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetOrderID")
    @RequestWrapper(localName = "GetOrderID", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.GetOrderID")
    @ResponseWrapper(localName = "GetOrderIDResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.GetOrderIDResponse")
    @WebResult(name = "GetOrderIDResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public java.lang.String getOrderID(
        @WebParam(name = "PNR", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String pnr
    );

    /**
     * 确认提醒信息
     */
    @WebMethod(operationName = "ConfirmOrderAlert", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/ConfirmOrderAlert")
    @RequestWrapper(localName = "ConfirmOrderAlert", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.ConfirmOrderAlert")
    @ResponseWrapper(localName = "ConfirmOrderAlertResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.ConfirmOrderAlertResponse")
    @WebResult(name = "ConfirmOrderAlertResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public boolean confirmOrderAlert(
        @WebParam(name = "orderAlert", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        com.medwin.landison.kms.reservationservice.OrderAlert orderAlert
    );

    /**
     * 将一个房间数大于1的订单拆分为多个订单并绑定PARTY关系
     */
    @WebMethod(operationName = "SplitOrderToParty", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/SplitOrderToParty")
    @RequestWrapper(localName = "SplitOrderToParty", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.SplitOrderToParty")
    @ResponseWrapper(localName = "SplitOrderToPartyResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.SplitOrderToPartyResponse")
    @WebResult(name = "SplitOrderToPartyResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.reservationservice.SplitOrderToPartyOut splitOrderToParty(
        @WebParam(name = "request", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        com.medwin.landison.kms.reservationservice.SplitOrderToPartyIn request
    );

    /**
     * 查询某个订单的备注信息
     */
    @WebMethod(operationName = "GetOrderInfoComments", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetOrderInfoComments")
    @RequestWrapper(localName = "GetOrderInfoComments", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.GetOrderInfoComments")
    @ResponseWrapper(localName = "GetOrderInfoCommentsResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.GetOrderInfoCommentsResponse")
    @WebResult(name = "GetOrderInfoCommentsResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.reservationservice.ArrayOfOrderInfoComments getOrderInfoComments(
        @WebParam(name = "OrderID", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        int orderID
    );

    /**
     * 新建订单,输入OrderInfo,输出OrderInfo
     */
    @WebMethod(operationName = "CreateReservation", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/CreateReservation")
    @RequestWrapper(localName = "CreateReservation", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.CreateReservation")
    @ResponseWrapper(localName = "CreateReservationResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.CreateReservationResponse")
    @WebResult(name = "CreateReservationResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.reservationservice.OrderInfo createReservation(
        @WebParam(name = "oOrderInfo", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        com.medwin.landison.kms.reservationservice.OrderInfo oOrderInfo
    );

    /**
     * 新建Pegasus订单,输入OrderInfo,输出OrderInfo
     */
    @WebMethod(operationName = "PegasusCreateReservation", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/PegasusCreateReservation")
    @RequestWrapper(localName = "PegasusCreateReservation", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.PegasusCreateReservation")
    @ResponseWrapper(localName = "PegasusCreateReservationResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.PegasusCreateReservationResponse")
    @WebResult(name = "PegasusCreateReservationResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.reservationservice.OrderInfo pegasusCreateReservation(
        @WebParam(name = "oOrderInfo", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        com.medwin.landison.kms.reservationservice.OrderInfo oOrderInfo
    );

    /**
     * 查询某个订单的trace信息
     */
    @WebMethod(operationName = "GetOrderInfoTrace", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetOrderInfoTrace")
    @RequestWrapper(localName = "GetOrderInfoTrace", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.GetOrderInfoTrace")
    @ResponseWrapper(localName = "GetOrderInfoTraceResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.GetOrderInfoTraceResponse")
    @WebResult(name = "GetOrderInfoTraceResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.reservationservice.GetOrderInfoTraceOut getOrderInfoTrace(
        @WebParam(name = "getOrderInfoTraceIn", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        com.medwin.landison.kms.reservationservice.GetOrderInfoTraceIn getOrderInfoTraceIn
    );

    /**
     * 解除一个已经存在PARTY关系的订单的PARTY关系
     */
    @WebMethod(operationName = "RemoveParty", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/RemoveParty")
    @RequestWrapper(localName = "RemoveParty", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.RemoveParty")
    @ResponseWrapper(localName = "RemovePartyResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.RemovePartyResponse")
    @WebResult(name = "RemovePartyResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.reservationservice.RemovePartyOut removeParty(
        @WebParam(name = "request", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        com.medwin.landison.kms.reservationservice.RemovePartyIn request
    );

    /**
     * Pegasus Deposits (payment) notification
     */
    @WebMethod(operationName = "PegasusSetDepositsNotification", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/PegasusSetDepositsNotification")
    @RequestWrapper(localName = "PegasusSetDepositsNotification", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.PegasusSetDepositsNotification")
    @ResponseWrapper(localName = "PegasusSetDepositsNotificationResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.PegasusSetDepositsNotificationResponse")
    @WebResult(name = "PegasusSetDepositsNotificationResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public boolean pegasusSetDepositsNotification(
        @WebParam(name = "oOrderInfo", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        com.medwin.landison.kms.reservationservice.OrderInfo oOrderInfo
    );

    /**
     * 将两个已经存在的订单关联PARTY关系
     */
    @WebMethod(operationName = "AddOrderToParty", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/AddOrderToParty")
    @RequestWrapper(localName = "AddOrderToParty", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.AddOrderToParty")
    @ResponseWrapper(localName = "AddOrderToPartyResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.AddOrderToPartyResponse")
    @WebResult(name = "AddOrderToPartyResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.reservationservice.AddOrderToPartyOut addOrderToParty(
        @WebParam(name = "request", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        com.medwin.landison.kms.reservationservice.AddOrderToPartyIn request
    );

    /**
     * 强制取消订单
     */
    @WebMethod(operationName = "CompelCancelReservation", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/CompelCancelReservation")
    @RequestWrapper(localName = "CompelCancelReservation", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.CompelCancelReservation")
    @ResponseWrapper(localName = "CompelCancelReservationResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.reservationservice.CompelCancelReservationResponse")
    @WebResult(name = "CompelCancelReservationResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public boolean compelCancelReservation(
        @WebParam(name = "id", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        int id,
        @WebParam(name = "comments", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String comments,
        @WebParam(name = "croPermission", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String croPermission
    );
}
