
package com.medwin.landison.kms.reservationservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-10-19T17:37:49.756+08:00
 * Generated source version: 3.2.6
 *
 */
public final class ReservationSoap_ReservationSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://www.shijinet.com.cn/kunlun/kws/1.1/", "Reservation");

    private ReservationSoap_ReservationSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = Reservation.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        Reservation ss = new Reservation(wsdlURL, SERVICE_NAME);
        ReservationSoap port = ss.getReservationSoap();

        {
        System.out.println("Invoking selfCheckInAllowed...");
        int _selfCheckInAllowed_id = 0;
        com.medwin.landison.kms.reservationservice.SelfCheckInAllowedInfo _selfCheckInAllowed__return = port.selfCheckInAllowed(_selfCheckInAllowed_id);
        System.out.println("selfCheckInAllowed.result=" + _selfCheckInAllowed__return);


        }
        {
        System.out.println("Invoking getOrderInfoAlert...");
        com.medwin.landison.kms.reservationservice.GetOrderInfoAlertIn _getOrderInfoAlert_getOrderInfoAlertIn = null;
        com.medwin.landison.kms.reservationservice.GetOrderInfoAlertOut _getOrderInfoAlert__return = port.getOrderInfoAlert(_getOrderInfoAlert_getOrderInfoAlertIn);
        System.out.println("getOrderInfoAlert.result=" + _getOrderInfoAlert__return);


        }
        {
        System.out.println("Invoking saveOrderInfoTrace...");
        com.medwin.landison.kms.reservationservice.SaveOrderInfoTraceIn _saveOrderInfoTrace_saveOrderInfoTraceIn = null;
        com.medwin.landison.kms.reservationservice.SaveOrderInfoTraceOut _saveOrderInfoTrace__return = port.saveOrderInfoTrace(_saveOrderInfoTrace_saveOrderInfoTraceIn);
        System.out.println("saveOrderInfoTrace.result=" + _saveOrderInfoTrace__return);


        }
        {
        System.out.println("Invoking getOrderInfoByGuestType...");
        java.lang.String _getOrderInfoByGuestType_guestType = "";
        java.lang.String _getOrderInfoByGuestType_account = "";
        javax.xml.datatype.XMLGregorianCalendar _getOrderInfoByGuestType_beginMakedate = null;
        javax.xml.datatype.XMLGregorianCalendar _getOrderInfoByGuestType_endMakedate = null;
        com.medwin.landison.kms.reservationservice.ArrayOfOrderInfo _getOrderInfoByGuestType__return = port.getOrderInfoByGuestType(_getOrderInfoByGuestType_guestType, _getOrderInfoByGuestType_account, _getOrderInfoByGuestType_beginMakedate, _getOrderInfoByGuestType_endMakedate);
        System.out.println("getOrderInfoByGuestType.result=" + _getOrderInfoByGuestType__return);


        }
        {
        System.out.println("Invoking addAndUpdateOrderInfoPaymentGateway...");
        com.medwin.landison.kms.reservationservice.OrderInfoPaymentGateway _addAndUpdateOrderInfoPaymentGateway_paymentGateway = null;
        java.lang.Integer _addAndUpdateOrderInfoPaymentGateway_id = null;
        boolean _addAndUpdateOrderInfoPaymentGateway_isRequiredCredit = false;
        java.lang.String _addAndUpdateOrderInfoPaymentGateway_creditId = "";
        java.lang.String _addAndUpdateOrderInfoPaymentGateway_cardHolder = "";
        javax.xml.datatype.XMLGregorianCalendar _addAndUpdateOrderInfoPaymentGateway_expire = null;
        boolean _addAndUpdateOrderInfoPaymentGateway_isCancelPayment = false;
        com.medwin.landison.kms.reservationservice.OrderInfoPaymentGateway _addAndUpdateOrderInfoPaymentGateway__return = port.addAndUpdateOrderInfoPaymentGateway(_addAndUpdateOrderInfoPaymentGateway_paymentGateway, _addAndUpdateOrderInfoPaymentGateway_id, _addAndUpdateOrderInfoPaymentGateway_isRequiredCredit, _addAndUpdateOrderInfoPaymentGateway_creditId, _addAndUpdateOrderInfoPaymentGateway_cardHolder, _addAndUpdateOrderInfoPaymentGateway_expire, _addAndUpdateOrderInfoPaymentGateway_isCancelPayment);
        System.out.println("addAndUpdateOrderInfoPaymentGateway.result=" + _addAndUpdateOrderInfoPaymentGateway__return);


        }
        {
        System.out.println("Invoking getOrderLogs...");
        int _getOrderLogs_id = 0;
        com.medwin.landison.kms.reservationservice.ArrayOfOrderLog _getOrderLogs__return = port.getOrderLogs(_getOrderLogs_id);
        System.out.println("getOrderLogs.result=" + _getOrderLogs__return);


        }
        {
        System.out.println("Invoking orderQuery...");
        int _orderQuery_id = 0;
        javax.xml.datatype.XMLGregorianCalendar _orderQuery_beginMakedate = null;
        javax.xml.datatype.XMLGregorianCalendar _orderQuery_endMakedate = null;
        javax.xml.datatype.XMLGregorianCalendar _orderQuery_arrival = null;
        javax.xml.datatype.XMLGregorianCalendar _orderQuery_departure = null;
        java.lang.String _orderQuery_statusCode = "";
        java.lang.String _orderQuery_reservationType = "";
        java.lang.String _orderQuery_hotelCode = "";
        java.lang.String _orderQuery_firstname = "";
        java.lang.String _orderQuery_lastname = "";
        java.lang.String _orderQuery_guestId = "";
        java.lang.String _orderQuery_account = "";
        java.lang.String _orderQuery_guestType = "";
        com.medwin.landison.kms.reservationservice.ArrayOfOrderInfo _orderQuery__return = port.orderQuery(_orderQuery_id, _orderQuery_beginMakedate, _orderQuery_endMakedate, _orderQuery_arrival, _orderQuery_departure, _orderQuery_statusCode, _orderQuery_reservationType, _orderQuery_hotelCode, _orderQuery_firstname, _orderQuery_lastname, _orderQuery_guestId, _orderQuery_account, _orderQuery_guestType);
        System.out.println("orderQuery.result=" + _orderQuery__return);


        }
        {
        System.out.println("Invoking saveOrderInfoAlert...");
        com.medwin.landison.kms.reservationservice.SaveOrderInfoAlertIn _saveOrderInfoAlert_saveOrderInfoAlertIn = null;
        com.medwin.landison.kms.reservationservice.SaveOrderInfoAlertOut _saveOrderInfoAlert__return = port.saveOrderInfoAlert(_saveOrderInfoAlert_saveOrderInfoAlertIn);
        System.out.println("saveOrderInfoAlert.result=" + _saveOrderInfoAlert__return);


        }
        {
        System.out.println("Invoking getOrderInfo...");
        int _getOrderInfo_id = 0;
        com.medwin.landison.kms.reservationservice.OrderInfo _getOrderInfo__return = port.getOrderInfo(_getOrderInfo_id);
        System.out.println("getOrderInfo.result=" + _getOrderInfo__return);


        }
        {
        System.out.println("Invoking addGiveUpOrderReserveReason...");
        com.medwin.landison.kms.reservationservice.GiveUpOrderReserveReasonIn _addGiveUpOrderReserveReason_cOrderReason = null;
        com.medwin.landison.kms.reservationservice.GiveUpOrderReserveReasonOut _addGiveUpOrderReserveReason__return = port.addGiveUpOrderReserveReason(_addGiveUpOrderReserveReason_cOrderReason);
        System.out.println("addGiveUpOrderReserveReason.result=" + _addGiveUpOrderReserveReason__return);


        }
        {
        System.out.println("Invoking changeReservationStatus...");
        com.medwin.landison.kms.reservationservice.ResvStatus _changeReservationStatus_status = null;
        int _changeReservationStatus_orderId = 0;
        boolean _changeReservationStatus__return = port.changeReservationStatus(_changeReservationStatus_status, _changeReservationStatus_orderId);
        System.out.println("changeReservationStatus.result=" + _changeReservationStatus__return);


        }
        {
        System.out.println("Invoking pegasusCancelReservation...");
        int _pegasusCancelReservation_id = 0;
        java.lang.String _pegasusCancelReservation_comments = "";
        java.lang.String _pegasusCancelReservation_channelCancelID = "";
        boolean _pegasusCancelReservation__return = port.pegasusCancelReservation(_pegasusCancelReservation_id, _pegasusCancelReservation_comments, _pegasusCancelReservation_channelCancelID);
        System.out.println("pegasusCancelReservation.result=" + _pegasusCancelReservation__return);


        }
        {
        System.out.println("Invoking getCancelRuleByOrderId...");
        java.lang.String _getCancelRuleByOrderId_orderId = "";
        com.medwin.landison.kms.reservationservice.CancelRule _getCancelRuleByOrderId__return = port.getCancelRuleByOrderId(_getCancelRuleByOrderId_orderId);
        System.out.println("getCancelRuleByOrderId.result=" + _getCancelRuleByOrderId__return);


        }
        {
        System.out.println("Invoking getOrderInfoByEmailAndID...");
        int _getOrderInfoByEmailAndID_id = 0;
        java.lang.String _getOrderInfoByEmailAndID_email = "";
        com.medwin.landison.kms.reservationservice.OrderInfo _getOrderInfoByEmailAndID__return = port.getOrderInfoByEmailAndID(_getOrderInfoByEmailAndID_id, _getOrderInfoByEmailAndID_email);
        System.out.println("getOrderInfoByEmailAndID.result=" + _getOrderInfoByEmailAndID__return);


        }
        {
        System.out.println("Invoking addorderInfoPaymentGateway...");
        com.medwin.landison.kms.reservationservice.OrderInfoPaymentGateway _addorderInfoPaymentGateway_paymentGateway = null;
        com.medwin.landison.kms.reservationservice.OrderInfoPaymentGateway _addorderInfoPaymentGateway__return = port.addorderInfoPaymentGateway(_addorderInfoPaymentGateway_paymentGateway);
        System.out.println("addorderInfoPaymentGateway.result=" + _addorderInfoPaymentGateway__return);


        }
        {
        System.out.println("Invoking pegasusModifyReservation...");
        com.medwin.landison.kms.reservationservice.OrderInfo _pegasusModifyReservation_oOrderInfo = null;
        com.medwin.landison.kms.reservationservice.OrderInfo _pegasusModifyReservation__return = port.pegasusModifyReservation(_pegasusModifyReservation_oOrderInfo);
        System.out.println("pegasusModifyReservation.result=" + _pegasusModifyReservation__return);


        }
        {
        System.out.println("Invoking cancelOrder...");
        int _cancelOrder_id = 0;
        java.lang.String _cancelOrder_comments = "";
        java.lang.String _cancelOrder_croPermission = "";
        boolean _cancelOrder__return = port.cancelOrder(_cancelOrder_id, _cancelOrder_comments, _cancelOrder_croPermission);
        System.out.println("cancelOrder.result=" + _cancelOrder__return);


        }
        {
        System.out.println("Invoking orderQueryPerPage...");
        int _orderQueryPerPage_id = 0;
        javax.xml.datatype.XMLGregorianCalendar _orderQueryPerPage_beginMakedate = null;
        javax.xml.datatype.XMLGregorianCalendar _orderQueryPerPage_endMakedate = null;
        javax.xml.datatype.XMLGregorianCalendar _orderQueryPerPage_arrival = null;
        javax.xml.datatype.XMLGregorianCalendar _orderQueryPerPage_departure = null;
        java.lang.String _orderQueryPerPage_statusCode = "";
        java.lang.String _orderQueryPerPage_reservationType = "";
        java.lang.String _orderQueryPerPage_hotelCode = "";
        java.lang.String _orderQueryPerPage_firstname = "";
        java.lang.String _orderQueryPerPage_lastname = "";
        java.lang.String _orderQueryPerPage_guestId = "";
        java.lang.String _orderQueryPerPage_account = "";
        java.lang.String _orderQueryPerPage_guestType = "";
        int _orderQueryPerPage_pageSize = 0;
        int _orderQueryPerPage_currentPage = 0;
        com.medwin.landison.kms.reservationservice.ExtraOrderInfoSummary _orderQueryPerPage__return = port.orderQueryPerPage(_orderQueryPerPage_id, _orderQueryPerPage_beginMakedate, _orderQueryPerPage_endMakedate, _orderQueryPerPage_arrival, _orderQueryPerPage_departure, _orderQueryPerPage_statusCode, _orderQueryPerPage_reservationType, _orderQueryPerPage_hotelCode, _orderQueryPerPage_firstname, _orderQueryPerPage_lastname, _orderQueryPerPage_guestId, _orderQueryPerPage_account, _orderQueryPerPage_guestType, _orderQueryPerPage_pageSize, _orderQueryPerPage_currentPage);
        System.out.println("orderQueryPerPage.result=" + _orderQueryPerPage__return);


        }
        {
        System.out.println("Invoking restoreReservation...");
        com.medwin.landison.kms.reservationservice.RestoreReservationIn _restoreReservation_restoreReservationIn = null;
        com.medwin.landison.kms.reservationservice.RestoreReservationOut _restoreReservation__return = port.restoreReservation(_restoreReservation_restoreReservationIn);
        System.out.println("restoreReservation.result=" + _restoreReservation__return);


        }
        {
        System.out.println("Invoking getOrderAlertList...");
        com.medwin.landison.kms.reservationservice.OrderAlertIn _getOrderAlertList_orderAlertIn = null;
        com.medwin.landison.kms.reservationservice.OrderAlertOut _getOrderAlertList__return = port.getOrderAlertList(_getOrderAlertList_orderAlertIn);
        System.out.println("getOrderAlertList.result=" + _getOrderAlertList__return);


        }
        {
        System.out.println("Invoking changeOrderStatus...");
        com.medwin.landison.kms.reservationservice.ResvStatus _changeOrderStatus_status = null;
        int _changeOrderStatus_orderId = 0;
        java.lang.String _changeOrderStatus_croPermission = "";
        boolean _changeOrderStatus__return = port.changeOrderStatus(_changeOrderStatus_status, _changeOrderStatus_orderId, _changeOrderStatus_croPermission);
        System.out.println("changeOrderStatus.result=" + _changeOrderStatus__return);


        }
        {
        System.out.println("Invoking queryOrderPage...");
        com.medwin.landison.kms.reservationservice.QueryOrderPageIn _queryOrderPage_request = null;
        com.medwin.landison.kms.reservationservice.QueryOrderPageOut _queryOrderPage__return = port.queryOrderPage(_queryOrderPage_request);
        System.out.println("queryOrderPage.result=" + _queryOrderPage__return);


        }
        {
        System.out.println("Invoking changeOrderToParty...");
        com.medwin.landison.kms.reservationservice.ChangeOrderToPartyIn _changeOrderToParty_request = null;
        com.medwin.landison.kms.reservationservice.ChangeOrderToPartyOut _changeOrderToParty__return = port.changeOrderToParty(_changeOrderToParty_request);
        System.out.println("changeOrderToParty.result=" + _changeOrderToParty__return);


        }
        {
        System.out.println("Invoking getOrderInfoDiscounts...");
        int _getOrderInfoDiscounts_orderID = 0;
        com.medwin.landison.kms.reservationservice.ArrayOfOrderInfoDiscount _getOrderInfoDiscounts__return = port.getOrderInfoDiscounts(_getOrderInfoDiscounts_orderID);
        System.out.println("getOrderInfoDiscounts.result=" + _getOrderInfoDiscounts__return);


        }
        {
        System.out.println("Invoking cancelReservation...");
        int _cancelReservation_id = 0;
        java.lang.String _cancelReservation_comments = "";
        boolean _cancelReservation__return = port.cancelReservation(_cancelReservation_id, _cancelReservation_comments);
        System.out.println("cancelReservation.result=" + _cancelReservation__return);


        }
        {
        System.out.println("Invoking modifyReservation...");
        com.medwin.landison.kms.reservationservice.OrderInfo _modifyReservation_oOrderInfo = null;
        com.medwin.landison.kms.reservationservice.OrderInfo _modifyReservation__return = port.modifyReservation(_modifyReservation_oOrderInfo);
        System.out.println("modifyReservation.result=" + _modifyReservation__return);


        }
        {
        System.out.println("Invoking getOrderID...");
        java.lang.String _getOrderID_pnr = "";
        java.lang.String _getOrderID__return = port.getOrderID(_getOrderID_pnr);
        System.out.println("getOrderID.result=" + _getOrderID__return);


        }
        {
        System.out.println("Invoking confirmOrderAlert...");
        com.medwin.landison.kms.reservationservice.OrderAlert _confirmOrderAlert_orderAlert = null;
        boolean _confirmOrderAlert__return = port.confirmOrderAlert(_confirmOrderAlert_orderAlert);
        System.out.println("confirmOrderAlert.result=" + _confirmOrderAlert__return);


        }
        {
        System.out.println("Invoking splitOrderToParty...");
        com.medwin.landison.kms.reservationservice.SplitOrderToPartyIn _splitOrderToParty_request = null;
        com.medwin.landison.kms.reservationservice.SplitOrderToPartyOut _splitOrderToParty__return = port.splitOrderToParty(_splitOrderToParty_request);
        System.out.println("splitOrderToParty.result=" + _splitOrderToParty__return);


        }
        {
        System.out.println("Invoking getOrderInfoComments...");
        int _getOrderInfoComments_orderID = 0;
        com.medwin.landison.kms.reservationservice.ArrayOfOrderInfoComments _getOrderInfoComments__return = port.getOrderInfoComments(_getOrderInfoComments_orderID);
        System.out.println("getOrderInfoComments.result=" + _getOrderInfoComments__return);


        }
        {
        System.out.println("Invoking createReservation...");
        com.medwin.landison.kms.reservationservice.OrderInfo _createReservation_oOrderInfo = null;
        com.medwin.landison.kms.reservationservice.OrderInfo _createReservation__return = port.createReservation(_createReservation_oOrderInfo);
        System.out.println("createReservation.result=" + _createReservation__return);


        }
        {
        System.out.println("Invoking pegasusCreateReservation...");
        com.medwin.landison.kms.reservationservice.OrderInfo _pegasusCreateReservation_oOrderInfo = null;
        com.medwin.landison.kms.reservationservice.OrderInfo _pegasusCreateReservation__return = port.pegasusCreateReservation(_pegasusCreateReservation_oOrderInfo);
        System.out.println("pegasusCreateReservation.result=" + _pegasusCreateReservation__return);


        }
        {
        System.out.println("Invoking getOrderInfoTrace...");
        com.medwin.landison.kms.reservationservice.GetOrderInfoTraceIn _getOrderInfoTrace_getOrderInfoTraceIn = null;
        com.medwin.landison.kms.reservationservice.GetOrderInfoTraceOut _getOrderInfoTrace__return = port.getOrderInfoTrace(_getOrderInfoTrace_getOrderInfoTraceIn);
        System.out.println("getOrderInfoTrace.result=" + _getOrderInfoTrace__return);


        }
        {
        System.out.println("Invoking removeParty...");
        com.medwin.landison.kms.reservationservice.RemovePartyIn _removeParty_request = null;
        com.medwin.landison.kms.reservationservice.RemovePartyOut _removeParty__return = port.removeParty(_removeParty_request);
        System.out.println("removeParty.result=" + _removeParty__return);


        }
        {
        System.out.println("Invoking pegasusSetDepositsNotification...");
        com.medwin.landison.kms.reservationservice.OrderInfo _pegasusSetDepositsNotification_oOrderInfo = null;
        boolean _pegasusSetDepositsNotification__return = port.pegasusSetDepositsNotification(_pegasusSetDepositsNotification_oOrderInfo);
        System.out.println("pegasusSetDepositsNotification.result=" + _pegasusSetDepositsNotification__return);


        }
        {
        System.out.println("Invoking addOrderToParty...");
        com.medwin.landison.kms.reservationservice.AddOrderToPartyIn _addOrderToParty_request = null;
        com.medwin.landison.kms.reservationservice.AddOrderToPartyOut _addOrderToParty__return = port.addOrderToParty(_addOrderToParty_request);
        System.out.println("addOrderToParty.result=" + _addOrderToParty__return);


        }
        {
        System.out.println("Invoking compelCancelReservation...");
        int _compelCancelReservation_id = 0;
        java.lang.String _compelCancelReservation_comments = "";
        java.lang.String _compelCancelReservation_croPermission = "";
        boolean _compelCancelReservation__return = port.compelCancelReservation(_compelCancelReservation_id, _compelCancelReservation_comments, _compelCancelReservation_croPermission);
        System.out.println("compelCancelReservation.result=" + _compelCancelReservation__return);


        }

        System.exit(0);
    }

}
