package com.medwin.landison.kms.availabilityservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-10-17T20:25:44.587+08:00
 * Generated source version: 3.2.6
 *
 */
@WebService(targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", name = "AvailabilityQuerySoap")
@XmlSeeAlso({ObjectFactory.class})
public interface AvailabilityQuerySoap {

    /**
     * 查询可单独销售的package，在某个订单上进行动态打包时选择
     */
    @WebMethod(operationName = "GetSeparateSoldPackage", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetSeparateSoldPackage")
    @RequestWrapper(localName = "GetSeparateSoldPackage", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.availabilityservice.GetSeparateSoldPackage")
    @ResponseWrapper(localName = "GetSeparateSoldPackageResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.availabilityservice.GetSeparateSoldPackageResponse")
    @WebResult(name = "GetSeparateSoldPackageResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.availabilityservice.SeparateSoldPackageOut getSeparateSoldPackage(
        @WebParam(name = "separateSoldPackageIn", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        com.medwin.landison.kms.availabilityservice.SeparateSoldPackageIn separateSoldPackageIn
    );

    /**
     * 获取某个酒店在某渠道的房价约束信息
     */
    @WebMethod(operationName = "GetRateRestrictions", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetRateRestrictions")
    @RequestWrapper(localName = "GetRateRestrictions", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.availabilityservice.GetRateRestrictions")
    @ResponseWrapper(localName = "GetRateRestrictionsResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.availabilityservice.GetRateRestrictionsResponse")
    @WebResult(name = "GetRateRestrictionsResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.availabilityservice.ArrayOfGetRateRestrictionsOut getRateRestrictions(
        @WebParam(name = "GetRateRestrictionsIn", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        com.medwin.landison.kms.availabilityservice.GetRateRestrictionsIn getRateRestrictionsIn
    );

    /**
     * 查询房价定义
     */
    @WebMethod(operationName = "GetRatePlan", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetRatePlan")
    @RequestWrapper(localName = "GetRatePlan", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.availabilityservice.GetRatePlan")
    @ResponseWrapper(localName = "GetRatePlanResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.availabilityservice.GetRatePlanResponse")
    @WebResult(name = "GetRatePlanResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.availabilityservice.ArrayOfRatePlan getRatePlan(
        @WebParam(name = "hotel_code", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String hotelCode,
        @WebParam(name = "room_type", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String roomType,
        @WebParam(name = "rate_code", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String rateCode,
        @WebParam(name = "begin_date", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        javax.xml.datatype.XMLGregorianCalendar beginDate,
        @WebParam(name = "end_date", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        javax.xml.datatype.XMLGregorianCalendar endDate
    );

    /**
     * 查询房型详情
     */
    @WebMethod(operationName = "GetRoomDetail", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetRoomDetail")
    @RequestWrapper(localName = "GetRoomDetail", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.availabilityservice.GetRoomDetail")
    @ResponseWrapper(localName = "GetRoomDetailResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.availabilityservice.GetRoomDetailResponse")
    @WebResult(name = "GetRoomDetailResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.availabilityservice.RoomTypeDetail getRoomDetail(
        @WebParam(name = "hotel_code", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String hotelCode,
        @WebParam(name = "roomtype_code", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String roomtypeCode
    );

    /**
     * 查询可用酒店房价详情,输入条件:房价最小价格,房价最大价格,入住时间,离店时间,加床,人数,房间数,客人类型,协议客户预订号,信用卡号,儿童数,渠道,集团code,国家code,城市code,地标名称,酒店名称,星级级别
     */
    @WebMethod(operationName = "GetAvailabilityList", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetAvailabilityList")
    @RequestWrapper(localName = "GetAvailabilityList", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.availabilityservice.GetAvailabilityList")
    @ResponseWrapper(localName = "GetAvailabilityListResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.availabilityservice.GetAvailabilityListResponse")
    @WebResult(name = "GetAvailabilityListResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.availabilityservice.ArrayOfAvailability getAvailabilityList(
        @WebParam(name = "min_price", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        int minPrice,
        @WebParam(name = "max_price", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        int maxPrice,
        @WebParam(name = "arrival", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        javax.xml.datatype.XMLGregorianCalendar arrival,
        @WebParam(name = "departure", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        javax.xml.datatype.XMLGregorianCalendar departure,
        @WebParam(name = "extra_bed", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        int extraBed,
        @WebParam(name = "adults", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        int adults,
        @WebParam(name = "room_num", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        int roomNum,
        @WebParam(name = "guesttype_code", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String guesttypeCode,
        @WebParam(name = "cust_account", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String custAccount,
        @WebParam(name = "card_no", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String cardNo,
        @WebParam(name = "children", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        int children,
        @WebParam(name = "channel", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String channel,
        @WebParam(name = "groupCode", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String groupCode,
        @WebParam(name = "countryCode", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String countryCode,
        @WebParam(name = "cityCode", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String cityCode,
        @WebParam(name = "tag", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String tag,
        @WebParam(name = "hotelName", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String hotelName,
        @WebParam(name = "starCode", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String starCode
    );

    /**
     * 根据房价类型查询单个酒店可用房型和房价（ARI）
     */
    @WebMethod(operationName = "GetBestAvailabilityARI", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetBestAvailabilityARI")
    @RequestWrapper(localName = "GetBestAvailabilityARI", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.availabilityservice.GetBestAvailabilityARI")
    @ResponseWrapper(localName = "GetBestAvailabilityARIResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.availabilityservice.GetBestAvailabilityARIResponse")
    @WebResult(name = "GetBestAvailabilityARIResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.availabilityservice.Availability getBestAvailabilityARI(
        @WebParam(name = "ARIRequest", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        com.medwin.landison.kms.availabilityservice.AvailabilityRequest ariRequest
    );

    /**
     * 查询房价详情概要
     */
    @WebMethod(operationName = "GetRateDetailSummary", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetRateDetailSummary")
    @RequestWrapper(localName = "GetRateDetailSummary", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.availabilityservice.GetRateDetailSummary")
    @ResponseWrapper(localName = "GetRateDetailSummaryResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.availabilityservice.GetRateDetailSummaryResponse")
    @WebResult(name = "GetRateDetailSummaryResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.availabilityservice.RateDetailSummary getRateDetailSummary(
        @WebParam(name = "hotel_code", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String hotelCode,
        @WebParam(name = "room_type", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String roomType,
        @WebParam(name = "rate_code", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String rateCode,
        @WebParam(name = "date", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        javax.xml.datatype.XMLGregorianCalendar date
    );

    /**
     * 加密解密字符(action：0解密，1加密)
     */
    @WebMethod(operationName = "GetEcryption", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetEcryption")
    @RequestWrapper(localName = "GetEcryption", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.availabilityservice.GetEcryption")
    @ResponseWrapper(localName = "GetEcryptionResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.availabilityservice.GetEcryptionResponse")
    @WebResult(name = "GetEcryptionResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public java.lang.String getEcryption(
        @WebParam(name = "key", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String key,
        @WebParam(name = "action", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        int action
    );

    /**
     * 检查房价及房型的可用性
     */
    @WebMethod(operationName = "CheckRateAndRoomTypeEnabled", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/CheckRateAndRoomTypeEnabled")
    @RequestWrapper(localName = "CheckRateAndRoomTypeEnabled", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.availabilityservice.CheckRateAndRoomTypeEnabled")
    @ResponseWrapper(localName = "CheckRateAndRoomTypeEnabledResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.availabilityservice.CheckRateAndRoomTypeEnabledResponse")
    @WebResult(name = "CheckRateAndRoomTypeEnabledResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.availabilityservice.CheckRateAndRoomTypeEnabledOut checkRateAndRoomTypeEnabled(
        @WebParam(name = "checkRateAndRoomTypeEnabledIn", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        com.medwin.landison.kms.availabilityservice.CheckRateAndRoomTypeEnabledIn checkRateAndRoomTypeEnabledIn
    );

    /**
     * 查询房价开关
     */
    @WebMethod(operationName = "GetRateSwitch", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetRateSwitch")
    @RequestWrapper(localName = "GetRateSwitch", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.availabilityservice.GetRateSwitch")
    @ResponseWrapper(localName = "GetRateSwitchResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.availabilityservice.GetRateSwitchResponse")
    @WebResult(name = "GetRateSwitchResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.availabilityservice.RateSwitch getRateSwitch(
        @WebParam(name = "hotel_code", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String hotelCode,
        @WebParam(name = "channel_code", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String channelCode,
        @WebParam(name = "rate_code", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String rateCode,
        @WebParam(name = "year", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        int year
    );

    /**
     * 查询可用酒店房价详情,输入条件:房价最小价格,房价最大价格,入住时间,离店时间,加床,人数,房间数,客人类型,协议客户预订号,信用卡号,儿童数,渠道,集团code,国家code,城市code,地标名称,酒店名称,星级级别
     */
    @WebMethod(operationName = "GetAvailabilityListByCustom", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetAvailabilityListByCustom")
    @RequestWrapper(localName = "GetAvailabilityListByCustom", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.availabilityservice.GetAvailabilityListByCustom")
    @ResponseWrapper(localName = "GetAvailabilityListByCustomResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.availabilityservice.GetAvailabilityListByCustomResponse")
    @WebResult(name = "GetAvailabilityListByCustomResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.availabilityservice.ArrayOfAvailability getAvailabilityListByCustom(
        @WebParam(name = "min_price", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        int minPrice,
        @WebParam(name = "max_price", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        int maxPrice,
        @WebParam(name = "arrival", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        javax.xml.datatype.XMLGregorianCalendar arrival,
        @WebParam(name = "departure", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        javax.xml.datatype.XMLGregorianCalendar departure,
        @WebParam(name = "extra_bed", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        int extraBed,
        @WebParam(name = "adults", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        int adults,
        @WebParam(name = "room_num", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        int roomNum,
        @WebParam(name = "guesttype_code", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String guesttypeCode,
        @WebParam(name = "cust_account", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String custAccount,
        @WebParam(name = "card_no", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String cardNo,
        @WebParam(name = "children", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        int children,
        @WebParam(name = "channel", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String channel,
        @WebParam(name = "groupCode", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String groupCode,
        @WebParam(name = "countryCode", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String countryCode,
        @WebParam(name = "cityCode", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String cityCode,
        @WebParam(name = "tag", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String tag,
        @WebParam(name = "hotelName", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String hotelName,
        @WebParam(name = "starCode", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String starCode
    );

    /**
     * 根据客人选择的可单独销售的某个package，计算它的每日详情和总价
     */
    @WebMethod(operationName = "CalculateSeparateSoldPackage", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/CalculateSeparateSoldPackage")
    @RequestWrapper(localName = "CalculateSeparateSoldPackage", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.availabilityservice.CalculateSeparateSoldPackage")
    @ResponseWrapper(localName = "CalculateSeparateSoldPackageResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.availabilityservice.CalculateSeparateSoldPackageResponse")
    @WebResult(name = "CalculateSeparateSoldPackageResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.availabilityservice.CalculationSeparateSoldPackageOut calculateSeparateSoldPackage(
        @WebParam(name = "calculationSeparateSoldPackageIn", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        com.medwin.landison.kms.availabilityservice.CalculationSeparateSoldPackageIn calculationSeparateSoldPackageIn
    );

    /**
     * 根据房价类型(DBarRate)查询某房型的每日房价详情
     */
    @WebMethod(operationName = "GetBestRateDetailDaily", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetBestRateDetailDaily")
    @RequestWrapper(localName = "GetBestRateDetailDaily", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.availabilityservice.GetBestRateDetailDaily")
    @ResponseWrapper(localName = "GetBestRateDetailDailyResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.availabilityservice.GetBestRateDetailDailyResponse")
    @WebResult(name = "GetBestRateDetailDailyResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.availabilityservice.RateInfo getBestRateDetailDaily(
        @WebParam(name = "rateDetailRequest", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        com.medwin.landison.kms.availabilityservice.RateDetailRequest rateDetailRequest
    );

    /**
     * 查询可用酒店房价详情(过滤酒店CODE),输入条件:入住时间,离店时间,加床数,人数,房间数,客人类型,协议客户预订号,信用卡号,儿童数,渠道,酒店code数组
     */
    @WebMethod(operationName = "NewGetAvailabilityListByCustom", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/NewGetAvailabilityListByCustom")
    @RequestWrapper(localName = "NewGetAvailabilityListByCustom", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.availabilityservice.NewGetAvailabilityListByCustom")
    @ResponseWrapper(localName = "NewGetAvailabilityListByCustomResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.availabilityservice.NewGetAvailabilityListByCustomResponse")
    @WebResult(name = "NewGetAvailabilityListByCustomResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.availabilityservice.ArrayOfAvailability newGetAvailabilityListByCustom(
        @WebParam(name = "arrival", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        javax.xml.datatype.XMLGregorianCalendar arrival,
        @WebParam(name = "departure", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        javax.xml.datatype.XMLGregorianCalendar departure,
        @WebParam(name = "extra_bed", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        int extraBed,
        @WebParam(name = "adults", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        int adults,
        @WebParam(name = "room_num", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        int roomNum,
        @WebParam(name = "guesttype_code", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String guesttypeCode,
        @WebParam(name = "cust_account", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String custAccount,
        @WebParam(name = "card_no", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String cardNo,
        @WebParam(name = "children", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        int children,
        @WebParam(name = "channel", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String channel,
        @WebParam(name = "hotelArr", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        com.medwin.landison.kms.availabilityservice.ArrayOfString hotelArr
    );

    /**
     * 查询酒店列表,输入房价最小价格,房价最大价格,入住时间,离店时间,加床,人数,房间数,客人类型,协议客户预订号,信用卡号,儿童数,渠道,集团code,国家code,城市code,地标名称,酒店名称,星级级别
     */
    @WebMethod(operationName = "HotelAvail", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/HotelAvail")
    @RequestWrapper(localName = "HotelAvail", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.availabilityservice.HotelAvail")
    @ResponseWrapper(localName = "HotelAvailResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.availabilityservice.HotelAvailResponse")
    @WebResult(name = "HotelAvailResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.availabilityservice.ArrayOfHotelInfoSummary hotelAvail(
        @WebParam(name = "request", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        com.medwin.landison.kms.availabilityservice.HotelAvailIn request
    );

    /**
     * 根据房价类型查询单个酒店房型和房价详情
     */
    @WebMethod(operationName = "GetBestAvailability", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetBestAvailability")
    @RequestWrapper(localName = "GetBestAvailability", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.availabilityservice.GetBestAvailability")
    @ResponseWrapper(localName = "GetBestAvailabilityResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.availabilityservice.GetBestAvailabilityResponse")
    @WebResult(name = "GetBestAvailabilityResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.availabilityservice.Availability getBestAvailability(
        @WebParam(name = "availabilityRequest", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        com.medwin.landison.kms.availabilityservice.AvailabilityRequest availabilityRequest
    );

    /**
     * 查询某房型的每日房价详情
     */
    @WebMethod(operationName = "GetRateDetailDaily", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetRateDetailDaily")
    @RequestWrapper(localName = "GetRateDetailDaily", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.availabilityservice.GetRateDetailDaily")
    @ResponseWrapper(localName = "GetRateDetailDailyResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.availabilityservice.GetRateDetailDailyResponse")
    @WebResult(name = "GetRateDetailDailyResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.availabilityservice.RateInfo getRateDetailDaily(
        @WebParam(name = "hotel_code", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String hotelCode,
        @WebParam(name = "channel_code", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String channelCode,
        @WebParam(name = "arrival", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        javax.xml.datatype.XMLGregorianCalendar arrival,
        @WebParam(name = "departure", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        javax.xml.datatype.XMLGregorianCalendar departure,
        @WebParam(name = "rooms", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        int rooms,
        @WebParam(name = "rate_code", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String rateCode,
        @WebParam(name = "room_type", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String roomType
    );

    /**
     * 查询可用房价酒店code列表,输入房价最小价格,房价最大价格,入住时间,离店时间,加床,人数,房间数,客人类型,协议客户预订号,信用卡号,儿童数,渠道,集团code,国家code,城市code,地标名称,酒店名称,星级级别
     */
    @WebMethod(operationName = "GetAvailabilityHotels", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetAvailabilityHotels")
    @RequestWrapper(localName = "GetAvailabilityHotels", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.availabilityservice.GetAvailabilityHotels")
    @ResponseWrapper(localName = "GetAvailabilityHotelsResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.availabilityservice.GetAvailabilityHotelsResponse")
    @WebResult(name = "GetAvailabilityHotelsResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.availabilityservice.ArrayOfString getAvailabilityHotels(
        @WebParam(name = "min_price", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        int minPrice,
        @WebParam(name = "max_price", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        int maxPrice,
        @WebParam(name = "arrival", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        javax.xml.datatype.XMLGregorianCalendar arrival,
        @WebParam(name = "departure", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        javax.xml.datatype.XMLGregorianCalendar departure,
        @WebParam(name = "extra_bed", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        int extraBed,
        @WebParam(name = "adults", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        int adults,
        @WebParam(name = "room_num", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        int roomNum,
        @WebParam(name = "guesttype_code", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String guesttypeCode,
        @WebParam(name = "cust_account", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String custAccount,
        @WebParam(name = "card_no", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String cardNo,
        @WebParam(name = "children", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        int children,
        @WebParam(name = "channel", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String channel,
        @WebParam(name = "groupCode", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String groupCode,
        @WebParam(name = "countryCode", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String countryCode,
        @WebParam(name = "cityCode", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String cityCode,
        @WebParam(name = "tag", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String tag,
        @WebParam(name = "hotelName", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String hotelName,
        @WebParam(name = "starCode", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String starCode
    );

    /**
     * 获取可以额外单独选择的所有item的信息
     */
    @WebMethod(operationName = "GetSeparateSoldItems", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetSeparateSoldItems")
    @RequestWrapper(localName = "GetSeparateSoldItems", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.availabilityservice.GetSeparateSoldItems")
    @ResponseWrapper(localName = "GetSeparateSoldItemsResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.availabilityservice.GetSeparateSoldItemsResponse")
    @WebResult(name = "GetSeparateSoldItemsResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.availabilityservice.SeparateSoldItemOut getSeparateSoldItems(
        @WebParam(name = "getItemIn", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        com.medwin.landison.kms.availabilityservice.SeparateSoldItemIn getItemIn
    );

    /**
     * 分页查询可用酒店房价详情,输入条件:房价最小价格,房价最大价格,入住时间,离店时间,加床,人数,房间数,客人类型,协议客户预订号,信用卡号,儿童数,渠道,集团code,国家code,城市code,地标名称,酒店名称,星级级别，每页数量，第几页
     */
    @WebMethod(operationName = "GetAvailabilityListPerPage", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetAvailabilityListPerPage")
    @RequestWrapper(localName = "GetAvailabilityListPerPage", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.availabilityservice.GetAvailabilityListPerPage")
    @ResponseWrapper(localName = "GetAvailabilityListPerPageResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.availabilityservice.GetAvailabilityListPerPageResponse")
    @WebResult(name = "GetAvailabilityListPerPageResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.availabilityservice.ExtraAvailability getAvailabilityListPerPage(
        @WebParam(name = "min_price", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        int minPrice,
        @WebParam(name = "max_price", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        int maxPrice,
        @WebParam(name = "arrival", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        javax.xml.datatype.XMLGregorianCalendar arrival,
        @WebParam(name = "departure", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        javax.xml.datatype.XMLGregorianCalendar departure,
        @WebParam(name = "extra_bed", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        int extraBed,
        @WebParam(name = "adults", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        int adults,
        @WebParam(name = "room_num", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        int roomNum,
        @WebParam(name = "guesttype_code", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String guesttypeCode,
        @WebParam(name = "cust_account", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String custAccount,
        @WebParam(name = "card_no", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String cardNo,
        @WebParam(name = "children", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        int children,
        @WebParam(name = "channel", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String channel,
        @WebParam(name = "groupCode", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String groupCode,
        @WebParam(name = "countryCode", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String countryCode,
        @WebParam(name = "cityCode", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String cityCode,
        @WebParam(name = "tag", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String tag,
        @WebParam(name = "hotelName", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String hotelName,
        @WebParam(name = "starCode", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String starCode,
        @WebParam(name = "pageSize", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        int pageSize,
        @WebParam(name = "currentPage", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        int currentPage
    );

    /**
     * 返回某个酒店的房型和可用房量
     */
    @WebMethod(operationName = "GetAvailabilityInventory", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetAvailabilityInventory")
    @RequestWrapper(localName = "GetAvailabilityInventory", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.availabilityservice.GetAvailabilityInventory")
    @ResponseWrapper(localName = "GetAvailabilityInventoryResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.availabilityservice.GetAvailabilityInventoryResponse")
    @WebResult(name = "GetAvailabilityInventoryResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.availabilityservice.AvailabilityInventory getAvailabilityInventory(
        @WebParam(name = "hotel_code", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String hotelCode,
        @WebParam(name = "arrival", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        javax.xml.datatype.XMLGregorianCalendar arrival,
        @WebParam(name = "departure", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        javax.xml.datatype.XMLGregorianCalendar departure,
        @WebParam(name = "channel", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String channel,
        @WebParam(name = "room_num", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        int roomNum
    );

    /**
     * 查询单个酒店房型和房价详情
     */
    @WebMethod(operationName = "GetAvailability", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetAvailability")
    @RequestWrapper(localName = "GetAvailability", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.availabilityservice.GetAvailability")
    @ResponseWrapper(localName = "GetAvailabilityResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.availabilityservice.GetAvailabilityResponse")
    @WebResult(name = "GetAvailabilityResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.availabilityservice.Availability getAvailability(
        @WebParam(name = "hotel_code", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String hotelCode,
        @WebParam(name = "arrival", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String  arrival,
        @WebParam(name = "departure", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String departure,
        @WebParam(name = "extra_bed", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        int extraBed,
        @WebParam(name = "adults", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        int adults,
        @WebParam(name = "room_num", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        int roomNum,
        @WebParam(name = "guesttype_code", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String guesttypeCode,
        @WebParam(name = "cust_account", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String custAccount,
        @WebParam(name = "card_no", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String cardNo,
        @WebParam(name = "children", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        int children,
        @WebParam(name = "channel", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String channel
    );

    /**
     * 获取日常库存信息
     */
    @WebMethod(operationName = "GetItemDailyInventory", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetItemDailyInventory")
    @RequestWrapper(localName = "GetItemDailyInventory", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.availabilityservice.GetItemDailyInventory")
    @ResponseWrapper(localName = "GetItemDailyInventoryResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.availabilityservice.GetItemDailyInventoryResponse")
    @WebResult(name = "GetItemDailyInventoryResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.availabilityservice.GetItemDailyInventoryOut getItemDailyInventory(
        @WebParam(name = "getItemDailyInventoryIn", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        com.medwin.landison.kms.availabilityservice.GetItemDailyInventoryIn getItemDailyInventoryIn
    );

    /**
     * 查询单个酒店某房价的房型和房价详情
     */
    @WebMethod(operationName = "GetAvailabilitybyRateCode", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetAvailabilitybyRateCode")
    @RequestWrapper(localName = "GetAvailabilitybyRateCode", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.availabilityservice.GetAvailabilitybyRateCode")
    @ResponseWrapper(localName = "GetAvailabilitybyRateCodeResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.availabilityservice.GetAvailabilitybyRateCodeResponse")
    @WebResult(name = "GetAvailabilitybyRateCodeResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.availabilityservice.Availability getAvailabilitybyRateCode(
        @WebParam(name = "rateRequest", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        com.medwin.landison.kms.availabilityservice.GetAvailabilitybyRateCodeIn rateRequest
    );

    /**
     * 查询某个房价中的Package和Item信息，用于查询可用房结果后，循环房价详情来获得房价中绑定的package和Item信息
     */
    @WebMethod(operationName = "GetAvailabilityPackage", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetAvailabilityPackage")
    @RequestWrapper(localName = "GetAvailabilityPackage", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.availabilityservice.GetAvailabilityPackage")
    @ResponseWrapper(localName = "GetAvailabilityPackageResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.availabilityservice.GetAvailabilityPackageResponse")
    @WebResult(name = "GetAvailabilityPackageResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.availabilityservice.GetAvailabilityPackageOut getAvailabilityPackage(
        @WebParam(name = "getAvailabilityPackageIn", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        com.medwin.landison.kms.availabilityservice.GetAvailabilityPackageIn getAvailabilityPackageIn
    );

    /**
     * 查询渠道房态信息
     */
    @WebMethod(operationName = "GetDailyInventory", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetDailyInventory")
    @RequestWrapper(localName = "GetDailyInventory", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.availabilityservice.GetDailyInventory")
    @ResponseWrapper(localName = "GetDailyInventoryResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.availabilityservice.GetDailyInventoryResponse")
    @WebResult(name = "GetDailyInventoryResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.availabilityservice.HotelDailyInventory getDailyInventory(
        @WebParam(name = "hotel_code", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String hotelCode,
        @WebParam(name = "channel", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String channel,
        @WebParam(name = "dtBegin", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        javax.xml.datatype.XMLGregorianCalendar dtBegin,
        @WebParam(name = "dtEnd", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        javax.xml.datatype.XMLGregorianCalendar dtEnd,
        @WebParam(name = "room_type", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String roomType
    );

    /**
     * 判断item库存是否足够
     */
    @WebMethod(operationName = "CheckItemIsEnough", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/CheckItemIsEnough")
    @RequestWrapper(localName = "CheckItemIsEnough", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.availabilityservice.CheckItemIsEnough")
    @ResponseWrapper(localName = "CheckItemIsEnoughResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.availabilityservice.CheckItemIsEnoughResponse")
    @WebResult(name = "CheckItemIsEnoughResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.availabilityservice.ArrayOfCheckItemIsEnoughOut checkItemIsEnough(
        @WebParam(name = "checkItemIsEnoughIn", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        com.medwin.landison.kms.availabilityservice.CheckItemIsEnoughIn checkItemIsEnoughIn
    );
}
