package com.medwin.landison.kms.availabilityservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2019-01-03T18:10:17.651+08:00
 * Generated source version: 3.2.6
 *
 */
@WebServiceClient(name = "AvailabilityQuery",
                  wsdlLocation = "http://116.62.146.178:9000/KWS_TRAIN/AvailabilityService.asmx?wsdl",
                  targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
public class AvailabilityQuery extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.shijinet.com.cn/kunlun/kws/1.1/", "AvailabilityQuery");
    public final static QName AvailabilityQuerySoap = new QName("http://www.shijinet.com.cn/kunlun/kws/1.1/", "AvailabilityQuerySoap");
    static {
        URL url = null;
        try {
            url = new URL("http://116.62.146.178:9000/KWS_TRAIN/AvailabilityService.asmx?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AvailabilityQuery.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://116.62.146.178:9000/KWS_TRAIN/AvailabilityService.asmx?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AvailabilityQuery(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AvailabilityQuery(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AvailabilityQuery() {
        super(WSDL_LOCATION, SERVICE);
    }

    public AvailabilityQuery(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public AvailabilityQuery(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public AvailabilityQuery(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns AvailabilityQuerySoap
     */
    @WebEndpoint(name = "AvailabilityQuerySoap")
    public AvailabilityQuerySoap getAvailabilityQuerySoap() {
        return super.getPort(AvailabilityQuerySoap, AvailabilityQuerySoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AvailabilityQuerySoap
     */
    @WebEndpoint(name = "AvailabilityQuerySoap")
    public AvailabilityQuerySoap getAvailabilityQuerySoap(WebServiceFeature... features) {
        return super.getPort(AvailabilityQuerySoap, AvailabilityQuerySoap.class, features);
    }

}
