package com.medwin.landison.kms.informationservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-10-17T20:06:09.556+08:00
 * Generated source version: 3.2.6
 *
 */
@WebServiceClient(name = "InformationService",
                  wsdlLocation = "file:/E:/github/landison/src/main/java/com/medwin/landison/kms/informationservice/InformationService.asmx",
                  targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
public class InformationService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.shijinet.com.cn/kunlun/kws/1.1/", "InformationService");
    public final static QName InformationServiceSoap = new QName("http://www.shijinet.com.cn/kunlun/kws/1.1/", "InformationServiceSoap");
    static {
        URL url = null;
        try {
            url = new URL("file:/E:/github/landison/src/main/java/com/medwin/landison/kms/informationservice/InformationService.asmx");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(InformationService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/E:/github/landison/src/main/java/com/medwin/landison/kms/informationservice/InformationService.asmx");
        }
        WSDL_LOCATION = url;
    }

    public InformationService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public InformationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InformationService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public InformationService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public InformationService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public InformationService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns InformationServiceSoap
     */
    @WebEndpoint(name = "InformationServiceSoap")
    public InformationServiceSoap getInformationServiceSoap() {
        return super.getPort(InformationServiceSoap, InformationServiceSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InformationServiceSoap
     */
    @WebEndpoint(name = "InformationServiceSoap")
    public InformationServiceSoap getInformationServiceSoap(WebServiceFeature... features) {
        return super.getPort(InformationServiceSoap, InformationServiceSoap.class, features);
    }

}
