package com.medwin.landison.kms.informationservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-10-17T20:06:09.511+08:00
 * Generated source version: 3.2.6
 *
 */
@WebService(targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", name = "InformationServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface InformationServiceSoap {

    /**
     * 查询酒店地标,输入酒店Code
     */
    @WebMethod(operationName = "GetLandmarkByHotel", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetLandmarkByHotel")
    @RequestWrapper(localName = "GetLandmarkByHotel", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetLandmarkByHotel")
    @ResponseWrapper(localName = "GetLandmarkByHotelResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetLandmarkByHotelResponse")
    @WebResult(name = "GetLandmarkByHotelResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.informationservice.ArrayOfTagsInfo getLandmarkByHotel(
        @WebParam(name = "hotel_code", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String hotelCode,
        @WebParam(name = "type_code", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String typeCode
    );

    /**
     * 查询特殊需求
     */
    @WebMethod(operationName = "GetSpecials", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetSpecials")
    @RequestWrapper(localName = "GetSpecials", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetSpecials")
    @ResponseWrapper(localName = "GetSpecialsResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetSpecialsResponse")
    @WebResult(name = "GetSpecialsResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.informationservice.ArrayOfSpecials getSpecials(
        @WebParam(name = "HotelCode", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String hotelCode,
        @WebParam(name = "code", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String code,
        @WebParam(name = "channelCode", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String channelCode
    );

    /**
     * 查询酒店用户列表,输入酒店code,用户code,用户名,不填查询所有
     */
    @WebMethod(operationName = "GetHotelUsersByCode", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetHotelUsersByCode")
    @RequestWrapper(localName = "GetHotelUsersByCode", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetHotelUsersByCode")
    @ResponseWrapper(localName = "GetHotelUsersByCodeResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetHotelUsersByCodeResponse")
    @WebResult(name = "GetHotelUsersByCodeResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.informationservice.ArrayOfUserInfo getHotelUsersByCode(
        @WebParam(name = "hotel_code", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String hotelCode,
        @WebParam(name = "userCode", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String userCode,
        @WebParam(name = "userName", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String userName
    );

    /**
     * 获取酒店可用房型列表,输入酒店code
     */
    @WebMethod(operationName = "GetHotelRoomType", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetHotelRoomType")
    @RequestWrapper(localName = "GetHotelRoomType", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetHotelRoomType")
    @ResponseWrapper(localName = "GetHotelRoomTypeResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetHotelRoomTypeResponse")
    @WebResult(name = "GetHotelRoomTypeResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.informationservice.ArrayOfRoomTypeDetail getHotelRoomType(
        @WebParam(name = "hotelCode", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String hotelCode
    );

    /**
     * 查询酒店alert信息
     */
    @WebMethod(operationName = "GetAlertInfo", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetAlertInfo")
    @RequestWrapper(localName = "GetAlertInfo", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetAlertInfo")
    @ResponseWrapper(localName = "GetAlertInfoResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetAlertInfoResponse")
    @WebResult(name = "GetAlertInfoResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.informationservice.GetAlertInfoOut getAlertInfo(
        @WebParam(name = "getAlertInfoIn", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        com.medwin.landison.kms.informationservice.GetAlertInfoIn getAlertInfoIn
    );

    /**
     * 获得酒店接机方式
     */
    @WebMethod(operationName = "GetTransportation", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetTransportation")
    @RequestWrapper(localName = "GetTransportation", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetTransportation")
    @ResponseWrapper(localName = "GetTransportationResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetTransportationResponse")
    @WebResult(name = "GetTransportationResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.informationservice.GetTransportationOut getTransportation(
        @WebParam(name = "getTransportationIn", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        com.medwin.landison.kms.informationservice.GetTransportationIn getTransportationIn
    );

    /**
     * 查询星级信息
     */
    @WebMethod(operationName = "GetStarLevel", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetStarLevel")
    @RequestWrapper(localName = "GetStarLevel", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetStarLevel")
    @ResponseWrapper(localName = "GetStarLevelResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetStarLevelResponse")
    @WebResult(name = "GetStarLevelResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.informationservice.ArrayOfStarLevel getStarLevel();

    /**
     * 获取酒店信息列表,输入酒店code
     */
    @WebMethod(operationName = "GetHotelInfo", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetHotelInfo")
    @RequestWrapper(localName = "GetHotelInfo", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetHotelInfo")
    @ResponseWrapper(localName = "GetHotelInfoResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetHotelInfoResponse")
    @WebResult(name = "GetHotelInfoResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.informationservice.ArrayOfHotelInfo getHotelInfo(
        @WebParam(name = "hotelCode", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String hotelCode
    );

    /**
     * 查询信用卡类型
     */
    @WebMethod(operationName = "GetCardType", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetCardType")
    @RequestWrapper(localName = "GetCardType", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetCardType")
    @ResponseWrapper(localName = "GetCardTypeResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetCardTypeResponse")
    @WebResult(name = "GetCardTypeResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.informationservice.ArrayOfCardType getCardType();

    /**
     * 查询单个酒店信息, 输入酒店code
     */
    @WebMethod(operationName = "GetSingleHotelInfo", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetSingleHotelInfo")
    @RequestWrapper(localName = "GetSingleHotelInfo", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetSingleHotelInfo")
    @ResponseWrapper(localName = "GetSingleHotelInfoResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetSingleHotelInfoResponse")
    @WebResult(name = "GetSingleHotelInfoResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.informationservice.HotelInfo getSingleHotelInfo(
        @WebParam(name = "code", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String code
    );

    /**
     * 查询酒店特定房价信息
     */
    @WebMethod(operationName = "GetRate", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetRate")
    @RequestWrapper(localName = "GetRate", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetRate")
    @ResponseWrapper(localName = "GetRateResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetRateResponse")
    @WebResult(name = "GetRateResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.informationservice.Rate getRate(
        @WebParam(name = "code", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String code,
        @WebParam(name = "hotelCode", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String hotelCode
    );

    /**
     * 查询package
     */
    @WebMethod(operationName = "GetPackage", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetPackage")
    @RequestWrapper(localName = "GetPackage", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetPackage")
    @ResponseWrapper(localName = "GetPackageResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetPackageResponse")
    @WebResult(name = "GetPackageResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.informationservice.Package getPackage(
        @WebParam(name = "code", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String code
    );

    /**
     * 查询国家列表
     */
    @WebMethod(operationName = "GetCountry", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetCountry")
    @RequestWrapper(localName = "GetCountry", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetCountry")
    @ResponseWrapper(localName = "GetCountryResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetCountryResponse")
    @WebResult(name = "GetCountryResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.informationservice.ArrayOfCountry getCountry();

    /**
     * 利用crs中已定义的模板,预览某个模板的内容
     */
    @WebMethod(operationName = "PreviewMessageTemplate", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/PreviewMessageTemplate")
    @RequestWrapper(localName = "PreviewMessageTemplate", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.PreviewMessageTemplate")
    @ResponseWrapper(localName = "PreviewMessageTemplateResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.PreviewMessageTemplateResponse")
    @WebResult(name = "PreviewMessageTemplateResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.informationservice.GetMessageTemplateContentByKeyOut previewMessageTemplate(
        @WebParam(name = "orderId", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        int orderId,
        @WebParam(name = "notificationTempateId", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String notificationTempateId
    );

    /**
     * 获得酒店级的房价描述信息
     */
    @WebMethod(operationName = "GetHotelRateSimple", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetHotelRateSimple")
    @RequestWrapper(localName = "GetHotelRateSimple", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetHotelRateSimple")
    @ResponseWrapper(localName = "GetHotelRateSimpleResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetHotelRateSimpleResponse")
    @WebResult(name = "GetHotelRateSimpleResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.informationservice.GetHotelRateSimpleOut getHotelRateSimple(
        @WebParam(name = "getHotelRateSimple", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        com.medwin.landison.kms.informationservice.GetHotelRateSimpleIn getHotelRateSimple
    );

    /**
     * 获取CRS里的操作员,仅供CRO使用
     */
    @WebMethod(operationName = "GetBookersList", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetBookersList")
    @RequestWrapper(localName = "GetBookersList", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetBookersList")
    @ResponseWrapper(localName = "GetBookersListResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetBookersListResponse")
    @WebResult(name = "GetBookersListResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.informationservice.ArrayOfGetBookersOut getBookersList(
        @WebParam(name = "request", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        com.medwin.landison.kms.informationservice.GetBookersIn request
    );

    /**
     * 校验酒店是否启用了酒店接口
     */
    @WebMethod(operationName = "CheckHotelInterface", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/CheckHotelInterface")
    @RequestWrapper(localName = "CheckHotelInterface", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.CheckHotelInterface")
    @ResponseWrapper(localName = "CheckHotelInterfaceResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.CheckHotelInterfaceResponse")
    @WebResult(name = "CheckHotelInterfaceResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public boolean checkHotelInterface(
        @WebParam(name = "hotel_code", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String hotelCode
    );

    /**
     * 获取系统参数,输入系统参数code,酒店code
     */
    @WebMethod(operationName = "GetSysParamInfo", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetSysParamInfo")
    @RequestWrapper(localName = "GetSysParamInfo", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetSysParamInfo")
    @ResponseWrapper(localName = "GetSysParamInfoResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetSysParamInfoResponse")
    @WebResult(name = "GetSysParamInfoResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.informationservice.SysParamInfo getSysParamInfo(
        @WebParam(name = "code", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String code,
        @WebParam(name = "hotel_code", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String hotelCode
    );

    /**
     * 获得外发通知（邮件、短信、传真）历史的单条历史记录（发送历史上的详情）
     */
    @WebMethod(operationName = "GetSingleSendInfo", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetSingleSendInfo")
    @RequestWrapper(localName = "GetSingleSendInfo", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetSingleSendInfo")
    @ResponseWrapper(localName = "GetSingleSendInfoResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetSingleSendInfoResponse")
    @WebResult(name = "GetSingleSendInfoResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.informationservice.GetSendInfoByKeyOut getSingleSendInfo(
        @WebParam(name = "sendId", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        int sendId
    );

    /**
     * 获取CRS里的酒店,仅供CRO使用
     */
    @WebMethod(operationName = "GetHotelsList", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetHotelsList")
    @RequestWrapper(localName = "GetHotelsList", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetHotelsList")
    @ResponseWrapper(localName = "GetHotelsListResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetHotelsListResponse")
    @WebResult(name = "GetHotelsListResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.informationservice.ArrayOfGetHotelsOut getHotelsList();

    /**
     * 查询某酒店部门下的trace信息
     */
    @WebMethod(operationName = "GetTraceTexts", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetTraceTexts")
    @RequestWrapper(localName = "GetTraceTexts", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetTraceTexts")
    @ResponseWrapper(localName = "GetTraceTextsResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetTraceTextsResponse")
    @WebResult(name = "GetTraceTextsResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.informationservice.GetTraceTextsOut getTraceTexts(
        @WebParam(name = "getTraceTextsIn", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        com.medwin.landison.kms.informationservice.GetTraceTextsIn getTraceTextsIn
    );

    /**
     * 获取会员偏好
     */
    @WebMethod(operationName = "GetPreferences", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetPreferences")
    @RequestWrapper(localName = "GetPreferences", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetPreferences")
    @ResponseWrapper(localName = "GetPreferencesResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetPreferencesResponse")
    @WebResult(name = "GetPreferencesResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.informationservice.ArrayOfPreferenceGroup getPreferences(
        @WebParam(name = "preferencegroup_codes", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String preferencegroupCodes
    );

    /**
     * 获取item大类
     */
    @WebMethod(operationName = "GetItemClasses", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetItemClasses")
    @RequestWrapper(localName = "GetItemClasses", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetItemClasses")
    @ResponseWrapper(localName = "GetItemClassesResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetItemClassesResponse")
    @WebResult(name = "GetItemClassesResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.informationservice.GetItemClassOut getItemClasses();

    /**
     * 获取item信息
     */
    @WebMethod(operationName = "GetItemInfo", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetItemInfo")
    @RequestWrapper(localName = "GetItemInfo", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetItemInfo")
    @ResponseWrapper(localName = "GetItemInfoResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetItemInfoResponse")
    @WebResult(name = "GetItemInfoResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.informationservice.GetItemInfoOut getItemInfo(
        @WebParam(name = "getItemInfoIn", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        com.medwin.landison.kms.informationservice.GetItemInfoIn getItemInfoIn
    );

    /**
     * 新建邮件/传真/短信
     */
    @WebMethod(operationName = "AddSendInfo", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/AddSendInfo")
    @RequestWrapper(localName = "AddSendInfo", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.AddSendInfo")
    @ResponseWrapper(localName = "AddSendInfoResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.AddSendInfoResponse")
    @WebResult(name = "AddSendInfoResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public boolean addSendInfo(
        @WebParam(name = "info", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        com.medwin.landison.kms.informationservice.SendInfo info
    );

    /**
     * 获取没有启用酒店接口的数据
     */
    @WebMethod(operationName = "GetNotEnabledHotelInterface", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetNotEnabledHotelInterface")
    @RequestWrapper(localName = "GetNotEnabledHotelInterface", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetNotEnabledHotelInterface")
    @ResponseWrapper(localName = "GetNotEnabledHotelInterfaceResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetNotEnabledHotelInterfaceResponse")
    @WebResult(name = "GetNotEnabledHotelInterfaceResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.informationservice.ArrayOfCommonInfo getNotEnabledHotelInterface();

    /**
     * 查询预定规则
     */
    @WebMethod(operationName = "GetGuaranteeRulesByRateCode", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetGuaranteeRulesByRateCode")
    @RequestWrapper(localName = "GetGuaranteeRulesByRateCode", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetGuaranteeRulesByRateCode")
    @ResponseWrapper(localName = "GetGuaranteeRulesByRateCodeResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetGuaranteeRulesByRateCodeResponse")
    @WebResult(name = "GetGuaranteeRulesByRateCodeResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.informationservice.ArrayOfGuaranteeRule getGuaranteeRulesByRateCode(
        @WebParam(name = "hotel_code", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String hotelCode,
        @WebParam(name = "channel", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String channel,
        @WebParam(name = "rate_code", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String rateCode,
        @WebParam(name = "arrival", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        javax.xml.datatype.XMLGregorianCalendar arrival,
        @WebParam(name = "departure", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        javax.xml.datatype.XMLGregorianCalendar departure
    );

    /**
     * 查询市场
     */
    @WebMethod(operationName = "GetSegment", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetSegment")
    @RequestWrapper(localName = "GetSegment", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetSegment")
    @ResponseWrapper(localName = "GetSegmentResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetSegmentResponse")
    @WebResult(name = "GetSegmentResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.informationservice.ArrayOfSegment getSegment(
        @WebParam(name = "parent_code", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String parentCode
    );

    /**
     * 获得opera的部门信息
     */
    @WebMethod(operationName = "GetPmsDepartments", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetPmsDepartments")
    @RequestWrapper(localName = "GetPmsDepartments", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetPmsDepartments")
    @ResponseWrapper(localName = "GetPmsDepartmentsResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetPmsDepartmentsResponse")
    @WebResult(name = "GetPmsDepartmentsResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.informationservice.GetPmsDepartmentsOut getPmsDepartments(
        @WebParam(name = "getPmsDepartmentsIn", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        com.medwin.landison.kms.informationservice.GetPmsDepartmentsIn getPmsDepartmentsIn
    );

    /**
     * 根据某个订单、外发通知的规则获得通知模板id，用于在补发前展示给操作员（CRO）
     */
    @WebMethod(operationName = "GetMessageTempletsByRule", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetMessageTempletsByRule")
    @RequestWrapper(localName = "GetMessageTempletsByRule", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetMessageTempletsByRule")
    @ResponseWrapper(localName = "GetMessageTempletsByRuleResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetMessageTempletsByRuleResponse")
    @WebResult(name = "GetMessageTempletsByRuleResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.informationservice.MessageTemplets getMessageTempletsByRule(
        @WebParam(name = "getMessageTemplateByOrderRuleIn", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        com.medwin.landison.kms.informationservice.GetMessageTemplateByOrderRuleIn getMessageTemplateByOrderRuleIn
    );

    /**
     * 查询多个酒店信息,输入酒店code,酒店中或英名称,星级级别,地址,关键字,城市code,城市名称
     */
    @WebMethod(operationName = "GetHotels", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetHotels")
    @RequestWrapper(localName = "GetHotels", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetHotels")
    @ResponseWrapper(localName = "GetHotelsResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetHotelsResponse")
    @WebResult(name = "GetHotelsResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.informationservice.ArrayOfHotelInfoSummary getHotels(
        @WebParam(name = "code", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String code,
        @WebParam(name = "name", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String name,
        @WebParam(name = "stars", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String stars,
        @WebParam(name = "address", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String address,
        @WebParam(name = "keyword", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String keyword,
        @WebParam(name = "cityCode", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String cityCode,
        @WebParam(name = "cityName", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String cityName,
        @WebParam(name = "groupCode", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String groupCode
    );

    /**
     * 查询支付方式字典信息
     */
    @WebMethod(operationName = "GetPayment", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetPayment")
    @RequestWrapper(localName = "GetPayment", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetPayment")
    @ResponseWrapper(localName = "GetPaymentResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetPaymentResponse")
    @WebResult(name = "GetPaymentResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.informationservice.GetPaymentOut getPayment(
        @WebParam(name = "getPaymentIn", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        com.medwin.landison.kms.informationservice.GetPaymentIn getPaymentIn
    );

    /**
     * 查询地标,输入城市code
     */
    @WebMethod(operationName = "GetLandmarkByCity", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetLandmarkByCity")
    @RequestWrapper(localName = "GetLandmarkByCity", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetLandmarkByCity")
    @ResponseWrapper(localName = "GetLandmarkByCityResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetLandmarkByCityResponse")
    @WebResult(name = "GetLandmarkByCityResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.informationservice.ArrayOfTagsInfo getLandmarkByCity(
        @WebParam(name = "code", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String code
    );

    /**
     * 获得所有酒店的所在城市
     */
    @WebMethod(operationName = "GetHotelCity", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetHotelCity")
    @RequestWrapper(localName = "GetHotelCity", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetHotelCity")
    @ResponseWrapper(localName = "GetHotelCityResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetHotelCityResponse")
    @WebResult(name = "GetHotelCityResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.informationservice.GetHotelCityOut getHotelCity(
        @WebParam(name = "getHotelCityIn", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        com.medwin.landison.kms.informationservice.GetHotelCityIn getHotelCityIn
    );

    /**
     * 获取称呼字典中的数据,返回code,name,gender字段
     */
    @WebMethod(operationName = "GetTitle", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetTitle")
    @RequestWrapper(localName = "GetTitle", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetTitle")
    @ResponseWrapper(localName = "GetTitleResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetTitleResponse")
    @WebResult(name = "GetTitleResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.informationservice.GetTitleOut getTitle(
        @WebParam(name = "getTitleByKeyIn", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        com.medwin.landison.kms.informationservice.GetTitleIn getTitleByKeyIn
    );

    /**
     * 获得外发通知（邮件、短信、传真）历史，可根据订单id或其他数据标识查询
     */
    @WebMethod(operationName = "GetSendInfoByKey", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetSendInfoByKey")
    @RequestWrapper(localName = "GetSendInfoByKey", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetSendInfoByKey")
    @ResponseWrapper(localName = "GetSendInfoByKeyResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetSendInfoByKeyResponse")
    @WebResult(name = "GetSendInfoByKeyResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.informationservice.GetSendInfoByKeyOut getSendInfoByKey(
        @WebParam(name = "getSendInfoByKeyIn", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        com.medwin.landison.kms.informationservice.GetSendInfoByKeyIn getSendInfoByKeyIn
    );

    /**
     * 获得模板信息
     */
    @WebMethod(operationName = "GetMesageTemplates", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetMesageTemplates")
    @RequestWrapper(localName = "GetMesageTemplates", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetMesageTemplates")
    @ResponseWrapper(localName = "GetMesageTemplatesResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetMesageTemplatesResponse")
    @WebResult(name = "GetMesageTemplatesResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.informationservice.GetMessageTempletsOut getMesageTemplates(
        @WebParam(name = "request", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        com.medwin.landison.kms.informationservice.GetMessageTempletsIn request
    );

    /**
     * 获取发布的房价及定义了房价的房型信息
     */
    @WebMethod(operationName = "GetPublishRateAndRoomtype", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetPublishRateAndRoomtype")
    @RequestWrapper(localName = "GetPublishRateAndRoomtype", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetPublishRateAndRoomtype")
    @ResponseWrapper(localName = "GetPublishRateAndRoomtypeResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetPublishRateAndRoomtypeResponse")
    @WebResult(name = "GetPublishRateAndRoomtypeResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.informationservice.ArrayOfPublishRateAndRoomtype getPublishRateAndRoomtype(
        @WebParam(name = "request", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        com.medwin.landison.kms.informationservice.GetPublishRateAndRoomtypeIn request
    );

    /**
     * 查询单个预定规则
     */
    @WebMethod(operationName = "GetGuaranteeRule", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetGuaranteeRule")
    @RequestWrapper(localName = "GetGuaranteeRule", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetGuaranteeRule")
    @ResponseWrapper(localName = "GetGuaranteeRuleResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetGuaranteeRuleResponse")
    @WebResult(name = "GetGuaranteeRuleResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.informationservice.GuaranteeRule getGuaranteeRule(
        @WebParam(name = "code", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String code
    );

    /**
     * 判断协议客户,输入公司预订登陆帐号
     */
    @WebMethod(operationName = "CheckIsCorporation", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/CheckIsCorporation")
    @RequestWrapper(localName = "CheckIsCorporation", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.CheckIsCorporation")
    @ResponseWrapper(localName = "CheckIsCorporationResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.CheckIsCorporationResponse")
    @WebResult(name = "CheckIsCorporationResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public boolean checkIsCorporation(
        @WebParam(name = "account", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String account
    );

    /**
     * 查询城市列表,输入国家code
     */
    @WebMethod(operationName = "GetCityList", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetCityList")
    @RequestWrapper(localName = "GetCityList", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetCityList")
    @ResponseWrapper(localName = "GetCityListResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetCityListResponse")
    @WebResult(name = "GetCityListResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.informationservice.ArrayOfCity getCityList(
        @WebParam(name = "countryCode", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String countryCode
    );

    /**
     * 利用crs的模板，发送订单相关通知
     */
    @WebMethod(operationName = "SendOrderNoticeByTemplate", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/SendOrderNoticeByTemplate")
    @RequestWrapper(localName = "SendOrderNoticeByTemplate", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.SendOrderNoticeByTemplate")
    @ResponseWrapper(localName = "SendOrderNoticeByTemplateResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.SendOrderNoticeByTemplateResponse")
    @WebResult(name = "SendOrderNoticeByTemplateResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.informationservice.SendOrderNoticeByTemplateOut sendOrderNoticeByTemplate(
        @WebParam(name = "sendOrderNoticeByTemplateIn", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        com.medwin.landison.kms.informationservice.SendOrderNoticeByTemplateIn sendOrderNoticeByTemplateIn
    );

    /**
     * 获取酒店消费地点
     */
    @WebMethod(operationName = "GetPlaceCode", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetPlaceCode")
    @RequestWrapper(localName = "GetPlaceCode", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetPlaceCode")
    @ResponseWrapper(localName = "GetPlaceCodeResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetPlaceCodeResponse")
    @WebResult(name = "GetPlaceCodeResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.informationservice.GetPlacesOut getPlaceCode(
        @WebParam(name = "hotel_code", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String hotelCode
    );

    /**
     * 查询conversion
     */
    @WebMethod(operationName = "GetConvertValue", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetConvertValue")
    @RequestWrapper(localName = "GetConvertValue", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetConvertValue")
    @ResponseWrapper(localName = "GetConvertValueResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetConvertValueResponse")
    @WebResult(name = "GetConvertValueResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public java.lang.String getConvertValue(
        @WebParam(name = "channel", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String channel,
        @WebParam(name = "hotel_code", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String hotelCode,
        @WebParam(name = "datatype", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String datatype,
        @WebParam(name = "code", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String code,
        @WebParam(name = "flag", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String flag
    );

    /**
     * 查询字典表的code 和name
     */
    @WebMethod(operationName = "GetInformation", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetInformation")
    @RequestWrapper(localName = "GetInformation", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetInformation")
    @ResponseWrapper(localName = "GetInformationResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetInformationResponse")
    @WebResult(name = "GetInformationResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.informationservice.ArrayOfCommonInfo getInformation(
        @WebParam(name = "DataType", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String dataType,
        @WebParam(name = "ParentCode", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String parentCode
    );

    /**
     * 获取PMS和UDF的映射
     */
    @WebMethod(operationName = "GetPMSUDFMapping", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetPMSUDFMapping")
    @RequestWrapper(localName = "GetPMSUDFMapping", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetPMSUDFMapping")
    @ResponseWrapper(localName = "GetPMSUDFMappingResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetPMSUDFMappingResponse")
    @WebResult(name = "GetPMSUDFMappingResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.informationservice.ArrayOfUDFAndPMSMapping getPMSUDFMapping(
        @WebParam(name = "hotel_code", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String hotelCode
    );

    /**
     * 获取酒店图片信息列表,输入酒店code
     */
    @WebMethod(operationName = "GetAttachmentInfoByHotelCode", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetAttachmentInfoByHotelCode")
    @RequestWrapper(localName = "GetAttachmentInfoByHotelCode", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetAttachmentInfoByHotelCode")
    @ResponseWrapper(localName = "GetAttachmentInfoByHotelCodeResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetAttachmentInfoByHotelCodeResponse")
    @WebResult(name = "GetAttachmentInfoByHotelCodeResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.informationservice.ArrayOfAttachmentInfo getAttachmentInfoByHotelCode(
        @WebParam(name = "hotelCode", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String hotelCode
    );

    /**
     * 查询地标,输入地标类型,城市
     */
    @WebMethod(operationName = "GetLandmark", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetLandmark")
    @RequestWrapper(localName = "GetLandmark", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetLandmark")
    @ResponseWrapper(localName = "GetLandmarkResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetLandmarkResponse")
    @WebResult(name = "GetLandmarkResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.informationservice.ArrayOfTagsInfo getLandmark(
        @WebParam(name = "type_code", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String typeCode,
        @WebParam(name = "city_code", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String cityCode
    );

    /**
     * 获取CRS里的部门,仅供CRO使用
     */
    @WebMethod(operationName = "GetDepartmentsList", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetDepartmentsList")
    @RequestWrapper(localName = "GetDepartmentsList", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetDepartmentsList")
    @ResponseWrapper(localName = "GetDepartmentsListResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetDepartmentsListResponse")
    @WebResult(name = "GetDepartmentsListResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.informationservice.ArrayOfGetDepartmentsOut getDepartmentsList(
        @WebParam(name = "hotelCode", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String hotelCode
    );

    /**
     * 查询来源
     */
    @WebMethod(operationName = "GetSource", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetSource")
    @RequestWrapper(localName = "GetSource", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetSource")
    @ResponseWrapper(localName = "GetSourceResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetSourceResponse")
    @WebResult(name = "GetSourceResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.informationservice.ArrayOfSource getSource(
        @WebParam(name = "parent_code", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String parentCode
    );

    /**
     * 查询某酒店的常见问答信息
     */
    @WebMethod(operationName = "GetFaq", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetFaq")
    @RequestWrapper(localName = "GetFaq", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetFaq")
    @ResponseWrapper(localName = "GetFaqResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetFaqResponse")
    @WebResult(name = "GetFaqResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.informationservice.GetFaqOut getFaq(
        @WebParam(name = "getFaqIn", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        com.medwin.landison.kms.informationservice.GetFaqIn getFaqIn
    );

    /**
     * 查询省份列表
     */
    @WebMethod(operationName = "GetProvince", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetProvince")
    @RequestWrapper(localName = "GetProvince", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetProvince")
    @ResponseWrapper(localName = "GetProvinceResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetProvinceResponse")
    @WebResult(name = "GetProvinceResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.informationservice.ArrayOfProvince getProvince(
        @WebParam(name = "country_code", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String countryCode
    );

    /**
     * 获取酒店促销信息列表,输入酒店code，到店日期，限制标志
     */
    @WebMethod(operationName = "GetHotelPromotionInfo", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/GetHotelPromotionInfo")
    @RequestWrapper(localName = "GetHotelPromotionInfo", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetHotelPromotionInfo")
    @ResponseWrapper(localName = "GetHotelPromotionInfoResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.informationservice.GetHotelPromotionInfoResponse")
    @WebResult(name = "GetHotelPromotionInfoResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public com.medwin.landison.kms.informationservice.ArrayOfHotelPromotionInfo getHotelPromotionInfo(
        @WebParam(name = "hotelCode", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String hotelCode,
        @WebParam(name = "arrive", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        javax.xml.datatype.XMLGregorianCalendar arrive,
        @WebParam(name = "flag", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        int flag
    );
}
