
package com.medwin.landison.kms.informationservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-10-17T20:06:09.365+08:00
 * Generated source version: 3.2.6
 *
 */
public final class InformationServiceSoap_InformationServiceSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://www.shijinet.com.cn/kunlun/kws/1.1/", "InformationService");

    private InformationServiceSoap_InformationServiceSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = InformationService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        InformationService ss = new InformationService(wsdlURL, SERVICE_NAME);
        InformationServiceSoap port = ss.getInformationServiceSoap();

        {
        System.out.println("Invoking getLandmarkByHotel...");
        java.lang.String _getLandmarkByHotel_hotelCode = "";
        java.lang.String _getLandmarkByHotel_typeCode = "";
        com.medwin.landison.kms.informationservice.ArrayOfTagsInfo _getLandmarkByHotel__return = port.getLandmarkByHotel(_getLandmarkByHotel_hotelCode, _getLandmarkByHotel_typeCode);
        System.out.println("getLandmarkByHotel.result=" + _getLandmarkByHotel__return);


        }
        {
        System.out.println("Invoking getSpecials...");
        java.lang.String _getSpecials_hotelCode = "";
        java.lang.String _getSpecials_code = "";
        java.lang.String _getSpecials_channelCode = "";
        com.medwin.landison.kms.informationservice.ArrayOfSpecials _getSpecials__return = port.getSpecials(_getSpecials_hotelCode, _getSpecials_code, _getSpecials_channelCode);
        System.out.println("getSpecials.result=" + _getSpecials__return);


        }
        {
        System.out.println("Invoking getHotelUsersByCode...");
        java.lang.String _getHotelUsersByCode_hotelCode = "";
        java.lang.String _getHotelUsersByCode_userCode = "";
        java.lang.String _getHotelUsersByCode_userName = "";
        com.medwin.landison.kms.informationservice.ArrayOfUserInfo _getHotelUsersByCode__return = port.getHotelUsersByCode(_getHotelUsersByCode_hotelCode, _getHotelUsersByCode_userCode, _getHotelUsersByCode_userName);
        System.out.println("getHotelUsersByCode.result=" + _getHotelUsersByCode__return);


        }
        {
        System.out.println("Invoking getHotelRoomType...");
        java.lang.String _getHotelRoomType_hotelCode = "";
        com.medwin.landison.kms.informationservice.ArrayOfRoomTypeDetail _getHotelRoomType__return = port.getHotelRoomType(_getHotelRoomType_hotelCode);
        System.out.println("getHotelRoomType.result=" + _getHotelRoomType__return);


        }
        {
        System.out.println("Invoking getAlertInfo...");
        com.medwin.landison.kms.informationservice.GetAlertInfoIn _getAlertInfo_getAlertInfoIn = null;
        com.medwin.landison.kms.informationservice.GetAlertInfoOut _getAlertInfo__return = port.getAlertInfo(_getAlertInfo_getAlertInfoIn);
        System.out.println("getAlertInfo.result=" + _getAlertInfo__return);


        }
        {
        System.out.println("Invoking getTransportation...");
        com.medwin.landison.kms.informationservice.GetTransportationIn _getTransportation_getTransportationIn = null;
        com.medwin.landison.kms.informationservice.GetTransportationOut _getTransportation__return = port.getTransportation(_getTransportation_getTransportationIn);
        System.out.println("getTransportation.result=" + _getTransportation__return);


        }
        {
        System.out.println("Invoking getStarLevel...");
        com.medwin.landison.kms.informationservice.ArrayOfStarLevel _getStarLevel__return = port.getStarLevel();
        System.out.println("getStarLevel.result=" + _getStarLevel__return);


        }
        {
        System.out.println("Invoking getHotelInfo...");
        java.lang.String _getHotelInfo_hotelCode = "";
        com.medwin.landison.kms.informationservice.ArrayOfHotelInfo _getHotelInfo__return = port.getHotelInfo(_getHotelInfo_hotelCode);
        System.out.println("getHotelInfo.result=" + _getHotelInfo__return);


        }
        {
        System.out.println("Invoking getCardType...");
        com.medwin.landison.kms.informationservice.ArrayOfCardType _getCardType__return = port.getCardType();
        System.out.println("getCardType.result=" + _getCardType__return);


        }
        {
        System.out.println("Invoking getSingleHotelInfo...");
        java.lang.String _getSingleHotelInfo_code = "";
        com.medwin.landison.kms.informationservice.HotelInfo _getSingleHotelInfo__return = port.getSingleHotelInfo(_getSingleHotelInfo_code);
        System.out.println("getSingleHotelInfo.result=" + _getSingleHotelInfo__return);


        }
        {
        System.out.println("Invoking getRate...");
        java.lang.String _getRate_code = "";
        java.lang.String _getRate_hotelCode = "";
        com.medwin.landison.kms.informationservice.Rate _getRate__return = port.getRate(_getRate_code, _getRate_hotelCode);
        System.out.println("getRate.result=" + _getRate__return);


        }
        {
        System.out.println("Invoking getPackage...");
        java.lang.String _getPackage_code = "";
        com.medwin.landison.kms.informationservice.Package _getPackage__return = port.getPackage(_getPackage_code);
        System.out.println("getPackage.result=" + _getPackage__return);


        }
        {
        System.out.println("Invoking getCountry...");
        com.medwin.landison.kms.informationservice.ArrayOfCountry _getCountry__return = port.getCountry();
        System.out.println("getCountry.result=" + _getCountry__return);


        }
        {
        System.out.println("Invoking previewMessageTemplate...");
        int _previewMessageTemplate_orderId = 0;
        java.lang.String _previewMessageTemplate_notificationTempateId = "";
        com.medwin.landison.kms.informationservice.GetMessageTemplateContentByKeyOut _previewMessageTemplate__return = port.previewMessageTemplate(_previewMessageTemplate_orderId, _previewMessageTemplate_notificationTempateId);
        System.out.println("previewMessageTemplate.result=" + _previewMessageTemplate__return);


        }
        {
        System.out.println("Invoking getHotelRateSimple...");
        com.medwin.landison.kms.informationservice.GetHotelRateSimpleIn _getHotelRateSimple_getHotelRateSimple = null;
        com.medwin.landison.kms.informationservice.GetHotelRateSimpleOut _getHotelRateSimple__return = port.getHotelRateSimple(_getHotelRateSimple_getHotelRateSimple);
        System.out.println("getHotelRateSimple.result=" + _getHotelRateSimple__return);


        }
        {
        System.out.println("Invoking getBookersList...");
        com.medwin.landison.kms.informationservice.GetBookersIn _getBookersList_request = null;
        com.medwin.landison.kms.informationservice.ArrayOfGetBookersOut _getBookersList__return = port.getBookersList(_getBookersList_request);
        System.out.println("getBookersList.result=" + _getBookersList__return);


        }
        {
        System.out.println("Invoking checkHotelInterface...");
        java.lang.String _checkHotelInterface_hotelCode = "";
        boolean _checkHotelInterface__return = port.checkHotelInterface(_checkHotelInterface_hotelCode);
        System.out.println("checkHotelInterface.result=" + _checkHotelInterface__return);


        }
        {
        System.out.println("Invoking getSysParamInfo...");
        java.lang.String _getSysParamInfo_code = "";
        java.lang.String _getSysParamInfo_hotelCode = "";
        com.medwin.landison.kms.informationservice.SysParamInfo _getSysParamInfo__return = port.getSysParamInfo(_getSysParamInfo_code, _getSysParamInfo_hotelCode);
        System.out.println("getSysParamInfo.result=" + _getSysParamInfo__return);


        }
        {
        System.out.println("Invoking getSingleSendInfo...");
        int _getSingleSendInfo_sendId = 0;
        com.medwin.landison.kms.informationservice.GetSendInfoByKeyOut _getSingleSendInfo__return = port.getSingleSendInfo(_getSingleSendInfo_sendId);
        System.out.println("getSingleSendInfo.result=" + _getSingleSendInfo__return);


        }
        {
        System.out.println("Invoking getHotelsList...");
        com.medwin.landison.kms.informationservice.ArrayOfGetHotelsOut _getHotelsList__return = port.getHotelsList();
        System.out.println("getHotelsList.result=" + _getHotelsList__return);


        }
        {
        System.out.println("Invoking getTraceTexts...");
        com.medwin.landison.kms.informationservice.GetTraceTextsIn _getTraceTexts_getTraceTextsIn = null;
        com.medwin.landison.kms.informationservice.GetTraceTextsOut _getTraceTexts__return = port.getTraceTexts(_getTraceTexts_getTraceTextsIn);
        System.out.println("getTraceTexts.result=" + _getTraceTexts__return);


        }
        {
        System.out.println("Invoking getPreferences...");
        java.lang.String _getPreferences_preferencegroupCodes = "";
        com.medwin.landison.kms.informationservice.ArrayOfPreferenceGroup _getPreferences__return = port.getPreferences(_getPreferences_preferencegroupCodes);
        System.out.println("getPreferences.result=" + _getPreferences__return);


        }
        {
        System.out.println("Invoking getItemClasses...");
        com.medwin.landison.kms.informationservice.GetItemClassOut _getItemClasses__return = port.getItemClasses();
        System.out.println("getItemClasses.result=" + _getItemClasses__return);


        }
        {
        System.out.println("Invoking getItemInfo...");
        com.medwin.landison.kms.informationservice.GetItemInfoIn _getItemInfo_getItemInfoIn = null;
        com.medwin.landison.kms.informationservice.GetItemInfoOut _getItemInfo__return = port.getItemInfo(_getItemInfo_getItemInfoIn);
        System.out.println("getItemInfo.result=" + _getItemInfo__return);


        }
        {
        System.out.println("Invoking addSendInfo...");
        com.medwin.landison.kms.informationservice.SendInfo _addSendInfo_info = null;
        boolean _addSendInfo__return = port.addSendInfo(_addSendInfo_info);
        System.out.println("addSendInfo.result=" + _addSendInfo__return);


        }
        {
        System.out.println("Invoking getNotEnabledHotelInterface...");
        com.medwin.landison.kms.informationservice.ArrayOfCommonInfo _getNotEnabledHotelInterface__return = port.getNotEnabledHotelInterface();
        System.out.println("getNotEnabledHotelInterface.result=" + _getNotEnabledHotelInterface__return);


        }
        {
        System.out.println("Invoking getGuaranteeRulesByRateCode...");
        java.lang.String _getGuaranteeRulesByRateCode_hotelCode = "";
        java.lang.String _getGuaranteeRulesByRateCode_channel = "";
        java.lang.String _getGuaranteeRulesByRateCode_rateCode = "";
        javax.xml.datatype.XMLGregorianCalendar _getGuaranteeRulesByRateCode_arrival = null;
        javax.xml.datatype.XMLGregorianCalendar _getGuaranteeRulesByRateCode_departure = null;
        com.medwin.landison.kms.informationservice.ArrayOfGuaranteeRule _getGuaranteeRulesByRateCode__return = port.getGuaranteeRulesByRateCode(_getGuaranteeRulesByRateCode_hotelCode, _getGuaranteeRulesByRateCode_channel, _getGuaranteeRulesByRateCode_rateCode, _getGuaranteeRulesByRateCode_arrival, _getGuaranteeRulesByRateCode_departure);
        System.out.println("getGuaranteeRulesByRateCode.result=" + _getGuaranteeRulesByRateCode__return);


        }
        {
        System.out.println("Invoking getSegment...");
        java.lang.String _getSegment_parentCode = "";
        com.medwin.landison.kms.informationservice.ArrayOfSegment _getSegment__return = port.getSegment(_getSegment_parentCode);
        System.out.println("getSegment.result=" + _getSegment__return);


        }
        {
        System.out.println("Invoking getPmsDepartments...");
        com.medwin.landison.kms.informationservice.GetPmsDepartmentsIn _getPmsDepartments_getPmsDepartmentsIn = null;
        com.medwin.landison.kms.informationservice.GetPmsDepartmentsOut _getPmsDepartments__return = port.getPmsDepartments(_getPmsDepartments_getPmsDepartmentsIn);
        System.out.println("getPmsDepartments.result=" + _getPmsDepartments__return);


        }
        {
        System.out.println("Invoking getMessageTempletsByRule...");
        com.medwin.landison.kms.informationservice.GetMessageTemplateByOrderRuleIn _getMessageTempletsByRule_getMessageTemplateByOrderRuleIn = null;
        com.medwin.landison.kms.informationservice.MessageTemplets _getMessageTempletsByRule__return = port.getMessageTempletsByRule(_getMessageTempletsByRule_getMessageTemplateByOrderRuleIn);
        System.out.println("getMessageTempletsByRule.result=" + _getMessageTempletsByRule__return);


        }
        {
        System.out.println("Invoking getHotels...");
        java.lang.String _getHotels_code = "";
        java.lang.String _getHotels_name = "";
        java.lang.String _getHotels_stars = "";
        java.lang.String _getHotels_address = "";
        java.lang.String _getHotels_keyword = "";
        java.lang.String _getHotels_cityCode = "";
        java.lang.String _getHotels_cityName = "";
        java.lang.String _getHotels_groupCode = "";
        com.medwin.landison.kms.informationservice.ArrayOfHotelInfoSummary _getHotels__return = port.getHotels(_getHotels_code, _getHotels_name, _getHotels_stars, _getHotels_address, _getHotels_keyword, _getHotels_cityCode, _getHotels_cityName, _getHotels_groupCode);
        System.out.println("getHotels.result=" + _getHotels__return);


        }
        {
        System.out.println("Invoking getPayment...");
        com.medwin.landison.kms.informationservice.GetPaymentIn _getPayment_getPaymentIn = null;
        com.medwin.landison.kms.informationservice.GetPaymentOut _getPayment__return = port.getPayment(_getPayment_getPaymentIn);
        System.out.println("getPayment.result=" + _getPayment__return);


        }
        {
        System.out.println("Invoking getLandmarkByCity...");
        java.lang.String _getLandmarkByCity_code = "";
        com.medwin.landison.kms.informationservice.ArrayOfTagsInfo _getLandmarkByCity__return = port.getLandmarkByCity(_getLandmarkByCity_code);
        System.out.println("getLandmarkByCity.result=" + _getLandmarkByCity__return);


        }
        {
        System.out.println("Invoking getHotelCity...");
        com.medwin.landison.kms.informationservice.GetHotelCityIn _getHotelCity_getHotelCityIn = null;
        com.medwin.landison.kms.informationservice.GetHotelCityOut _getHotelCity__return = port.getHotelCity(_getHotelCity_getHotelCityIn);
        System.out.println("getHotelCity.result=" + _getHotelCity__return);


        }
        {
        System.out.println("Invoking getTitle...");
        com.medwin.landison.kms.informationservice.GetTitleIn _getTitle_getTitleByKeyIn = null;
        com.medwin.landison.kms.informationservice.GetTitleOut _getTitle__return = port.getTitle(_getTitle_getTitleByKeyIn);
        System.out.println("getTitle.result=" + _getTitle__return);


        }
        {
        System.out.println("Invoking getSendInfoByKey...");
        com.medwin.landison.kms.informationservice.GetSendInfoByKeyIn _getSendInfoByKey_getSendInfoByKeyIn = null;
        com.medwin.landison.kms.informationservice.GetSendInfoByKeyOut _getSendInfoByKey__return = port.getSendInfoByKey(_getSendInfoByKey_getSendInfoByKeyIn);
        System.out.println("getSendInfoByKey.result=" + _getSendInfoByKey__return);


        }
        {
        System.out.println("Invoking getMesageTemplates...");
        com.medwin.landison.kms.informationservice.GetMessageTempletsIn _getMesageTemplates_request = null;
        com.medwin.landison.kms.informationservice.GetMessageTempletsOut _getMesageTemplates__return = port.getMesageTemplates(_getMesageTemplates_request);
        System.out.println("getMesageTemplates.result=" + _getMesageTemplates__return);


        }
        {
        System.out.println("Invoking getPublishRateAndRoomtype...");
        com.medwin.landison.kms.informationservice.GetPublishRateAndRoomtypeIn _getPublishRateAndRoomtype_request = null;
        com.medwin.landison.kms.informationservice.ArrayOfPublishRateAndRoomtype _getPublishRateAndRoomtype__return = port.getPublishRateAndRoomtype(_getPublishRateAndRoomtype_request);
        System.out.println("getPublishRateAndRoomtype.result=" + _getPublishRateAndRoomtype__return);


        }
        {
        System.out.println("Invoking getGuaranteeRule...");
        java.lang.String _getGuaranteeRule_code = "";
        com.medwin.landison.kms.informationservice.GuaranteeRule _getGuaranteeRule__return = port.getGuaranteeRule(_getGuaranteeRule_code);
        System.out.println("getGuaranteeRule.result=" + _getGuaranteeRule__return);


        }
        {
        System.out.println("Invoking checkIsCorporation...");
        java.lang.String _checkIsCorporation_account = "";
        boolean _checkIsCorporation__return = port.checkIsCorporation(_checkIsCorporation_account);
        System.out.println("checkIsCorporation.result=" + _checkIsCorporation__return);


        }
        {
        System.out.println("Invoking getCityList...");
        java.lang.String _getCityList_countryCode = "";
        com.medwin.landison.kms.informationservice.ArrayOfCity _getCityList__return = port.getCityList(_getCityList_countryCode);
        System.out.println("getCityList.result=" + _getCityList__return);


        }
        {
        System.out.println("Invoking sendOrderNoticeByTemplate...");
        com.medwin.landison.kms.informationservice.SendOrderNoticeByTemplateIn _sendOrderNoticeByTemplate_sendOrderNoticeByTemplateIn = null;
        com.medwin.landison.kms.informationservice.SendOrderNoticeByTemplateOut _sendOrderNoticeByTemplate__return = port.sendOrderNoticeByTemplate(_sendOrderNoticeByTemplate_sendOrderNoticeByTemplateIn);
        System.out.println("sendOrderNoticeByTemplate.result=" + _sendOrderNoticeByTemplate__return);


        }
        {
        System.out.println("Invoking getPlaceCode...");
        java.lang.String _getPlaceCode_hotelCode = "";
        com.medwin.landison.kms.informationservice.GetPlacesOut _getPlaceCode__return = port.getPlaceCode(_getPlaceCode_hotelCode);
        System.out.println("getPlaceCode.result=" + _getPlaceCode__return);


        }
        {
        System.out.println("Invoking getConvertValue...");
        java.lang.String _getConvertValue_channel = "";
        java.lang.String _getConvertValue_hotelCode = "";
        java.lang.String _getConvertValue_datatype = "";
        java.lang.String _getConvertValue_code = "";
        java.lang.String _getConvertValue_flag = "";
        java.lang.String _getConvertValue__return = port.getConvertValue(_getConvertValue_channel, _getConvertValue_hotelCode, _getConvertValue_datatype, _getConvertValue_code, _getConvertValue_flag);
        System.out.println("getConvertValue.result=" + _getConvertValue__return);


        }
        {
        System.out.println("Invoking getInformation...");
        java.lang.String _getInformation_dataType = "";
        java.lang.String _getInformation_parentCode = "";
        com.medwin.landison.kms.informationservice.ArrayOfCommonInfo _getInformation__return = port.getInformation(_getInformation_dataType, _getInformation_parentCode);
        System.out.println("getInformation.result=" + _getInformation__return);


        }
        {
        System.out.println("Invoking getPMSUDFMapping...");
        java.lang.String _getPMSUDFMapping_hotelCode = "";
        com.medwin.landison.kms.informationservice.ArrayOfUDFAndPMSMapping _getPMSUDFMapping__return = port.getPMSUDFMapping(_getPMSUDFMapping_hotelCode);
        System.out.println("getPMSUDFMapping.result=" + _getPMSUDFMapping__return);


        }
        {
        System.out.println("Invoking getAttachmentInfoByHotelCode...");
        java.lang.String _getAttachmentInfoByHotelCode_hotelCode = "";
        com.medwin.landison.kms.informationservice.ArrayOfAttachmentInfo _getAttachmentInfoByHotelCode__return = port.getAttachmentInfoByHotelCode(_getAttachmentInfoByHotelCode_hotelCode);
        System.out.println("getAttachmentInfoByHotelCode.result=" + _getAttachmentInfoByHotelCode__return);


        }
        {
        System.out.println("Invoking getLandmark...");
        java.lang.String _getLandmark_typeCode = "";
        java.lang.String _getLandmark_cityCode = "";
        com.medwin.landison.kms.informationservice.ArrayOfTagsInfo _getLandmark__return = port.getLandmark(_getLandmark_typeCode, _getLandmark_cityCode);
        System.out.println("getLandmark.result=" + _getLandmark__return);


        }
        {
        System.out.println("Invoking getDepartmentsList...");
        java.lang.String _getDepartmentsList_hotelCode = "";
        com.medwin.landison.kms.informationservice.ArrayOfGetDepartmentsOut _getDepartmentsList__return = port.getDepartmentsList(_getDepartmentsList_hotelCode);
        System.out.println("getDepartmentsList.result=" + _getDepartmentsList__return);


        }
        {
        System.out.println("Invoking getSource...");
        java.lang.String _getSource_parentCode = "";
        com.medwin.landison.kms.informationservice.ArrayOfSource _getSource__return = port.getSource(_getSource_parentCode);
        System.out.println("getSource.result=" + _getSource__return);


        }
        {
        System.out.println("Invoking getFaq...");
        com.medwin.landison.kms.informationservice.GetFaqIn _getFaq_getFaqIn = null;
        com.medwin.landison.kms.informationservice.GetFaqOut _getFaq__return = port.getFaq(_getFaq_getFaqIn);
        System.out.println("getFaq.result=" + _getFaq__return);


        }
        {
        System.out.println("Invoking getProvince...");
        java.lang.String _getProvince_countryCode = "";
        com.medwin.landison.kms.informationservice.ArrayOfProvince _getProvince__return = port.getProvince(_getProvince_countryCode);
        System.out.println("getProvince.result=" + _getProvince__return);


        }
        {
        System.out.println("Invoking getHotelPromotionInfo...");
        java.lang.String _getHotelPromotionInfo_hotelCode = "";
        javax.xml.datatype.XMLGregorianCalendar _getHotelPromotionInfo_arrive = null;
        int _getHotelPromotionInfo_flag = 0;
        com.medwin.landison.kms.informationservice.ArrayOfHotelPromotionInfo _getHotelPromotionInfo__return = port.getHotelPromotionInfo(_getHotelPromotionInfo_hotelCode, _getHotelPromotionInfo_arrive, _getHotelPromotionInfo_flag);
        System.out.println("getHotelPromotionInfo.result=" + _getHotelPromotionInfo__return);


        }

        System.exit(0);
    }

}
