package com.medwin.landison.kms.securityservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-10-17T14:29:49.519+08:00
 * Generated source version: 3.2.6
 *
 */
@WebService(targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", name = "SecurityServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface SecurityServiceSoap {

    /**
     * 系统用户登录
     */
    @WebMethod(operationName = "AppLogin", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/AppLogin")
    @RequestWrapper(localName = "AppLogin", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.securityservice.AppLogin")
    @ResponseWrapper(localName = "AppLoginResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.securityservice.AppLoginResponse")
    @WebResult(name = "AppLoginResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public boolean appLogin(
        @WebParam(name = "username", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String username,
        @WebParam(name = "password", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String password,
        @WebParam(name = "encryptMethod", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String encryptMethod
    );

    /**
     * 系统用户登出注销Ver2.8SP420110630
     */
    @WebMethod(operationName = "AppLoginOut", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/AppLoginOut")
    @RequestWrapper(localName = "AppLoginOut", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.securityservice.AppLoginOut")
    @ResponseWrapper(localName = "AppLoginOutResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.securityservice.AppLoginOutResponse")
    @WebResult(name = "AppLoginOutResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public boolean appLoginOut(
        @WebParam(name = "sid", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String sid
    );

    /**
     * 系统用户修改密码
     */
    @WebMethod(operationName = "AppModifyPw", action = "http://www.shijinet.com.cn/kunlun/kws/1.1/AppModifyPw")
    @RequestWrapper(localName = "AppModifyPw", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.securityservice.AppModifyPw")
    @ResponseWrapper(localName = "AppModifyPwResponse", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/", className = "com.medwin.landison.kms.securityservice.AppModifyPwResponse")
    @WebResult(name = "AppModifyPwResult", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
    public boolean appModifyPw(
        @WebParam(name = "username", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String username,
        @WebParam(name = "password", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String password,
        @WebParam(name = "newpassword", targetNamespace = "http://www.shijinet.com.cn/kunlun/kws/1.1/")
        java.lang.String newpassword
    );
}
