
package com.medwin.landison.kms.securityservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-10-17T14:29:49.358+08:00
 * Generated source version: 3.2.6
 *
 */
public final class SecurityServiceSoap_SecurityServiceSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://www.shijinet.com.cn/kunlun/kws/1.1/", "SecurityService");

    private SecurityServiceSoap_SecurityServiceSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SecurityService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        SecurityService ss = new SecurityService(wsdlURL, SERVICE_NAME);
        SecurityServiceSoap port = ss.getSecurityServiceSoap();

        {
        System.out.println("Invoking appLogin...");
        java.lang.String _appLogin_username = "kws";
        java.lang.String _appLogin_password = "8888";
        java.lang.String _appLogin_encryptMethod = "";
        boolean _appLogin__return = port.appLogin(_appLogin_username, _appLogin_password, _appLogin_encryptMethod);
        System.out.println("appLogin.result=" + _appLogin__return);


        }
        {
        System.out.println("Invoking appLoginOut...");
        java.lang.String _appLoginOut_sid = "";
        boolean _appLoginOut__return = port.appLoginOut(_appLoginOut_sid);
        System.out.println("appLoginOut.result=" + _appLoginOut__return);


        }
        {
        System.out.println("Invoking appModifyPw...");
        java.lang.String _appModifyPw_username = "";
        java.lang.String _appModifyPw_password = "";
        java.lang.String _appModifyPw_newpassword = "";
        boolean _appModifyPw__return = port.appModifyPw(_appModifyPw_username, _appModifyPw_password, _appModifyPw_newpassword);
        System.out.println("appModifyPw.result=" + _appModifyPw__return);


        }

        System.exit(0);
    }

}
